/// Japanese translations for strings rendered by the native tray and
/// Dynamic Island. English source text is the key; see Localization.swift.
enum RouterJapaneseText {
  static let values: [String: String] = [
    "Uninstalling": "アンインストール中",
    "Off by default · compacts old results; RTK shapes routed compaction": "デフォルトでオフ · 古い結果を圧縮し、RTK がルーティング圧縮を整形します",
    "Fix Codex Router installation": "Codex ルーターのインストールを修復",
    "Language": "言語",
    "System": "システムに従う",
    "Tray language. Reopen the panel to apply everywhere.": "トレイの言語。パネルを開き直すとすべてに適用されます。",
    "Usage and activity over the notch on every display": "すべてのディスプレイのノッチ上に使用量とアクティビティを表示",
    "Off by default. The menu-bar panel stays available either way.": "デフォルトでオフ。いずれの場合もメニューバーパネルは利用できます。",
    "Idle": "待機中",
    "LOCAL FALLBACK": "ローカルフォールバック",
    "local fallback": "ローカルフォールバック",
    "%d local fallback dates": "ローカルフォールバック %d 日",
    "1 local fallback date": "ローカルフォールバック 1 日",
    "OpenAI account usage; missing dates use local router fallback": "OpenAI アカウント使用量。欠けている日はローカルルーターのフォールバックを使用します",
    "OpenAI supplied no account bucket for these dates; local router traffic fills the gap. These are not global account totals.": "OpenAI がこれらの日のアカウントバケットを提供していないため、ローカルルーターのトラフィックで補完します。グローバルなアカウント合計ではありません。",
    "Thinking": "思考中",
    "Starting": "起動中",
    "Error": "エラー",
    "Codex subscription": "Codex サブスクリプション",
    "%@ left": "残り %@",
    "%d chats": "%d 件のチャット",
    "Active session": "アクティブなセッション",
    "No traffic": "トラフィックなし",
    "Ready to enable": "有効化の準備完了",
    "Needs setup": "セットアップが必要",
    "OAuth · enabled": "OAuth · 有効",
    "API · enabled": "API · 有効",
    "Always": "常に表示",
    "With Codex": "Codex と一緒に表示",
    "Off": "オフ",
    "Notch": "ノッチ",
    "Desktop": "デスクトップ",
    "Usage": "使用量",
    "Usage and live activity": "使用量とライブアクティビティ",
    "Status": "状態",
    "Settings": "設定",
    "Control Center": "コントロールセンター",
    "Codex Router": "Codex Router",
    "Updated": "更新済み",
    "None": "なし",
    "none": "なし",
    "Local": "ローカル",
    "Auto": "自動",
    "Codex account": "Codex アカウント",
    "ChatGPT %@": "ChatGPT %@",
    "ChatGPT limit": "ChatGPT の上限",
    "Current usage": "現在の使用量",
    "All usage": "すべての使用量",
    "7-day snapshot": "過去 7 日間のスナップショット",
    "Tokens by model": "モデル別トークン",
    "Router": "ルーター",
    "Model speed": "モデル速度",
    "Live requests": "ライブリクエスト",
    "Quota resets": "割り当てのリセット",
    "No traffic right now": "現在トラフィックはありません",
    "Ready for the next request": "次のリクエストを待機中",
    "No model observed": "モデルはまだ観測されていません",
    "No usage recorded yet": "使用量はまだ記録されていません",
    "Waiting": "待機中",
    "No samples": "サンプルなし",
    "Appears after a metered reply": "計測対象の応答の後に表示されます",
    "Observed output throughput": "観測された出力速度",
    "Nothing in flight": "進行中のリクエストはありません",
    "no tools — can't chat": "ツールなし — チャット不可",
    "works in Codex": "Codex で動作",
    "unreliable in Codex": "Codex で不安定",
    "not offered yet": "まだ提供されていません",
    "fails in Codex": "Codex で失敗",
    "chat — untested": "チャット — 未テスト",
    "Provider added. Restart Codex to refresh its model picker.": "プロバイダーを追加しました。モデルピッカーを更新するには Codex を再起動してください。",
    "Provider hidden. Restart Codex to refresh its model picker.": "プロバイダーを非表示にしました。モデルピッカーを更新するには Codex を再起動してください。",
    "Show tray": "メニューバーアイコンを表示",
    "Appears with Codex or ChatGPT, hides when they quit": "Codex または ChatGPT の実行中に表示され、終了すると非表示になります",
    "Kept on: a terminal session has no window to follow": "常にオン：ターミナルセッションには追従するウィンドウがありません",
    "DeepSeek Harness": "DeepSeek Harness",
    "Install DeepSeek Harness and publish this router's models into it": "DeepSeek Harness をインストールし、このルーターのモデルを公開します",
    "Not installed · installs the CLI, then publishes this router's models": "未インストール · CLI をインストールし、このルーターのモデルを公開します",
    "Needs Node %@ or newer; this router runs Node %@": "Node %@ 以降が必要です。このルーターは Node %@ で動作しています",
    "%@ · routed models published · `dsh web` to start": "%@ · ルーティングされたモデルを公開済み · `dsh web` で起動",
    "%@ · installed but not routed here yet": "%@ · インストール済みですが、まだこのルーターに接続されていません",
    "%d models published. Run `%@` to start.": "%d 個のモデルを公開しました。`%@` を実行して起動してください。",
    "Installing DeepSeek Harness…": "DeepSeek Harness をインストール中…",
    "Publishing routed models…": "ルーティングされたモデルを公開中…",
    "Setting up DeepSeek Harness": "DeepSeek Harness をセットアップ中",
    "Connect": "接続",
    "Open site": "サイトを開く",
    "Turn off": "オフにする",
    "Disconnect": "接続を解除",
    "Stopping…": "停止中…",
    "Stopped. Memory and CPU released.": "停止しました。メモリと CPU を解放しました。",
    "This harness was started outside the router — stop it where you started it.": "この Harness はルーターの外部で起動されました — 起動した場所で停止してください。",
    "Stop the harness process and free its memory and CPU": "Harness プロセスを停止してメモリと CPU を解放",
    "Disconnecting…": "接続を解除中…",
    "Turned off. The harness and its own settings were kept.": "オフにしました。Harness とその設定は保持されています。",
    "Remove this router's models from the harness, keeping the harness itself": "Harness からこのルーターのモデルを削除し、Harness 自体は保持します",
    "Start": "起動",
    "Open the DeepSeek Harness browser UI": "DeepSeek Harness のブラウザ UI を開く",
    "Start the DeepSeek Harness browser UI": "DeepSeek Harness のブラウザ UI を起動",
    "Starting DeepSeek Harness…": "DeepSeek Harness を起動中…",
    "%@ · running at %@": "%@ · %@ で実行中",
    "%@ · routed models published · not running": "%@ · ルーティングされたモデルを公開済み · 未実行",
    "%d models published. Press play to open the harness.": "%d 個のモデルを公開しました。再生ボタンを押すと Harness が開きます。",
    "%d models published, but the harness UI did not start: %@": "%d 個のモデルを公開しましたが、Harness の UI を起動できませんでした：%@",
    "Menu bar icon stays visible": "メニューバーアイコンを常に表示",
    "Dynamic Island": "ダイナミックアイランド",
    "Quotas and live activity pinned to the desktop": "割り当てとライブアクティビティをデスクトップに固定",
    "Show provider usage and activity status": "プロバイダーの使用量とアクティビティ状態を表示",
    "Use Router with ChatGPT": "ChatGPT でルーターを使用",
    "Share ChatGPT subscription": "ChatGPT サブスクリプションを共有",
    "Sharing status unavailable": "共有状態を取得できません",
    "Sharing enabled": "共有は有効です",
    "Sharing disabled": "共有は無効です",
    "login usable · about %@h left": "ログインは利用可能です · 残り約 %@ 時間",
    "login usable": "ログインは利用可能です",
    "login expired": "ログインの有効期限が切れています",
    "login unavailable · sign-in data detected": "ログインは利用できません · サインインデータを検出しました",
    "login unavailable · run codex login": "ログインは利用できません · codex login を実行してください",
    "Enable ChatGPT session sharing?": "ChatGPT セッション共有を有効にしますか？",
    "Enabling lets other local Codex Router clients spend this user's ChatGPT subscription. Only continue for clients you trust on this Mac.": "有効にすると、ほかのローカル Codex Router クライアントがこのユーザーの ChatGPT サブスクリプションを消費できます。この Mac 上で信頼できるクライアントにのみ続行してください。",
    "Enable sharing": "共有を有効化",
    "A usable ChatGPT login is required before sharing can be enabled. Run codex login first.": "共有を有効にするには利用可能な ChatGPT ログインが必要です。先に codex login を実行してください。",
    "ChatGPT session-sharing status is unavailable. Refresh before changing it.": "ChatGPT セッション共有の状態を取得できません。変更前に更新してください。",
    "ChatGPT session sharing enabled for local router clients.": "ローカルのルータークライアント向けに ChatGPT セッション共有を有効にしました。",
    "ChatGPT session sharing disabled. Installed client catalogs were refreshed.": "ChatGPT セッション共有を無効にし、インストール済みクライアントのカタログを更新しました。",
    "Native GPT + external models · task history preserved": "ネイティブ GPT + 外部モデル · タスク履歴を保持",
    "Keep ChatGPT login and the current task history": "ChatGPT のログインと現在のタスク履歴を保持",
    "Use without OpenAI login": "OpenAI ログインなしで使用",
    "External providers · Codex restarts automatically": "外部プロバイダー · Codex は自動的に再起動します",
    "Use connected models and restart Codex": "接続済みモデルを使用して Codex を再起動",
    "Token maxxing": "Token maxxing",
    "Forced off by CODEX_ROUTER_TOOL_RESULT_AGING=0": "CODEX_ROUTER_TOOL_RESULT_AGING=0 により強制的に無効",
    "External models · applies on the next request": "外部モデル · 次回のリクエストから適用",
    "Providers": "プロバイダー",
    "Auto-saved": "自動保存済み",
    "Applying…": "適用中…",
    "Subagent models": "サブエージェントモデル",
    "All proven models": "すべての検証済みモデル",
    "Model picker": "モデルピッカー",
    "Local LLMs": "ローカル LLM",
    "Vision": "ビジョン",
    "Subagent choices do not hide models from Codex's picker — use Model picker below for that.": "サブエージェントの選択は Codex のピッカーからモデルを隠しません。非表示にするには下のモデルピッカーを使用してください。",
    "Hidden models stay connected but are not offered by Codex.": "非表示のモデルは接続されたままですが、Codex には提供されません。",
    "Run models locally through Ollama. Enable an installed model to make it available to Codex.": "Ollama を通じてモデルをローカルで実行します。インストール済みのモデルを有効にすると Codex で利用できます。",
    "Run local models through Ollama or the curated MLX runtime. Installed models are wired into the same Codex proxy.": "Ollama または厳選された MLX ランタイムでローカルモデルを実行します。インストール済みモデルは同じ Codex プロキシに接続されます。",
    "Nothing installed yet. Start with a quick pick or browse the Ollama catalog below.": "まだ何もインストールされていません。クイック選択から始めるか、下の Ollama カタログを参照してください。",
    "Install a model": "モデルをインストール",
    "Install": "インストール",
    "Clear": "クリア",
    "Download": "ダウンロード",
    "Cancel": "キャンセル",
    "Confirm": "確認",
    "Confirm removal?": "削除を確認しますか？",
    "Remove model": "モデルを削除",
    "Measure speed": "速度を測定",
    "Test image reading": "画像読み取りをテスト",
    "Use for image reading": "画像読み取りに使用",
    "Reading images": "画像を読み取り中",
    "loaded": "読み込み済み",
    "Installing local model": "ローカルモデルをインストール中",
    "Local model ready": "ローカルモデルの準備完了",
    "Local model install failed": "ローカルモデルのインストールに失敗しました",
    "Text-only models can't see images. When on, a vision model reads the paste and hands over the text.": "テキスト専用モデルは画像を認識できません。オンにすると、ビジョンモデルが貼り付けた内容を読み取り、テキストとして渡します。",
    "Read images for text-only models": "テキスト専用モデルのために画像を読み取る",
    "Engine": "エンジン",
    "Paid (cloud)": "有料（クラウド）",
    "Your ChatGPT plan": "あなたの ChatGPT プラン",
    "Cannot run subagents": "サブエージェントを実行できません",
    "Effort as subagent": "サブエージェント時の推論強度",
    "Model default": "モデルのデフォルト",
    "Update": "アップデート",
    "Fix": "修復",
    "Working…": "処理中…",
    "Update or fix failed": "アップデートまたは修復に失敗しました",
    "Router unavailable": "ルーターを利用できません",
    "Run setup, then refresh this panel.": "セットアップを実行してから、このパネルを更新してください。",
    "Refresh": "更新",
    "Refreshing…": "更新中…",
    "%d accounts": "%d 件のアカウント",
    "1 account": "1 件のアカウント",
    "Restart": "再起動",
    "Restarting…": "再起動中…",
    "Restart failed: %@": "再起動に失敗しました：%@",
    "Restarted without updating: %@": "アップデートせずに再起動しました：%@",
    "Awaiting data": "データ待ち",
    "Quit": "終了",
    "API key": "API キー",
    "Replacement %@": "置き換え用の%@",
    "Paste %@": "%@を貼り付け",
    "Click the check again to delete this credential": "チェックをもう一度クリックすると、この資格情報を削除します",
    "Checking setup…": "セットアップを確認中…",
    "Session expired · reconnect for account usage": "セッションの有効期限が切れました · アカウント使用量を見るには再接続してください",
    "Official CLI required": "公式 CLI が必要",
    "Sign in with the official CLI": "公式 CLI でサインイン",
    "Operator-owned Google OAuth client required": "オペレーター所有の Google OAuth クライアントが必要",
    "Live test required · sends a small prompt and uses quota": "ライブテストが必要 · 短いプロンプトを送信し、クォータを消費します",
    "Disconnect the incompatible router record before signing in": "互換性のないルーター資格情報を切断してからサインインしてください",
    "Setup required": "セットアップが必要",
    "Reconnect": "再接続",
    "Reconnect OAuth": "OAuth を再接続",
    "Open browser sign-in": "ブラウザでサインインを開く",
    "Finish sign-in in browser": "ブラウザでサインインを完了",
    "OAuth sessions refresh automatically. Reconnect opens browser sign-in when approval is required.": "OAuth セッションは自動更新されます。再認証が必要な場合は、再接続するとブラウザのサインインが開きます。",
    "Install & Sign In": "インストールしてサインイン",
    "Sign In": "サインイン",
    "Install the official CLI and sign in": "公式 CLI をインストールしてサインイン",
    "Sign in again with the official CLI": "公式 CLI でもう一度サインイン",
    "Cancel credential replacement": "資格情報の置き換えをキャンセル",
    "Click again to delete the stored credential": "もう一度クリックすると、保存された資格情報を削除します",
    "Remove stored OAuth client and session": "保存された OAuth クライアントとセッションを削除",
    "Test & Enable": "テストして有効化",
    "Remove stored %@": "保存された%@を削除",
    "Available in Codex": "Codex で利用可能",
    "Hidden from Codex": "Codex から非表示",
    "Signed in": "サインイン済み",
    "Add Key": "キーを追加",
    "Save": "保存",
    "Open usage dashboard": "使用量ダッシュボードを開く",
    "Daily token usage": "日次トークン使用量",
    "Full": "完全",
    "Full token numbers": "完全なトークン数",
    "Millions of tokens": "百万トークン単位",
    "Token unit": "トークン単位",
    "Router traffic": "ルータートラフィック",
    "Loading provider usage…": "プロバイダーの使用量を読み込み中…",
    "Loading native Codex usage…": "ネイティブ Codex の使用量を読み込み中…",
    "Set up this provider below to fetch its account usage.": "アカウント使用量を取得するには、下でこのプロバイダーをセットアップしてください。",
    "Usage limit": "使用量の上限",
    "No reset reported": "リセット時刻の報告なし",
    "Reconnect below": "下で再接続してください",
    "OAuth expired · reconnect below": "OAuth の有効期限が切れました · 下で再接続してください",
    "No router traffic yet": "ルータートラフィックはまだありません",
    "Configured · currently hidden": "設定済み · 現在非表示",
    "Sign in again to restore quota": "割り当てを復元するにはもう一度サインインしてください",
    "Local router traffic": "ローカルルーターのトラフィック",
    "What do these tags mean?": "これらのタグの意味は？",
    "Hide tag guide": "タグの説明を隠す",
    "Show fewer tags": "タグを折りたたむ",
    "View all %@ tags": "%@ 個のタグをすべて表示",
    "Hide machine & runtime": "マシンとランタイムを隠す",
    "Machine & runtime": "マシンとランタイム",
    "Show fewer quick picks": "クイック選択を折りたたむ",
    "View more quick picks": "クイック選択をもっと見る",
    "Show all": "すべて表示",
    "Hide all": "すべて非表示",
    "Update and verify Codex Router": "Codex ルーターをアップデートして検証",
    "Running Codex Router maintenance": "Codex ルーターをメンテナンス中",
    "Daily token usage chart. Hover a day for its displayed token count.": "日次トークン使用量グラフ。日にカーソルを合わせると表示中のトークン数を確認できます。",
    "Show %@ usage": "%@ の使用量を表示",
    "WEEKLY LEFT": "週間残り",
    "TODAY TOKENS": "今日のトークン",
    "DAILY USAGE": "日次使用量",
    "LAST 7 DAYS": "過去 7 日間",
    "Collapse": "折りたたむ",
    "TODAY'S TOKENS": "今日のトークン",
    "DAILY TOKEN TREND": "日次トークン推移",
    "ACTIVE NOW": "現在アクティブ",
    "ACTIVE PROVIDER": "アクティブなプロバイダー",
    "USED": "使用済み",
    "Account and traffic are provider-scoped": "アカウントとトラフィックはプロバイダーごとに区分されます",
    "Live": "ライブ",
    "Last used": "最終使用",
    "Running chats": "実行中のチャット",
    "Router overview": "ルーター概要",
    "Ready": "準備完了",
    "CHATGPT • NATIVE": "CHATGPT · ネイティブ",
    "XAI • OAUTH SESSION": "XAI · OAUTH セッション",
    "XAI • METERED API": "XAI · 従量制 API",
    "METERED API": "従量制 API",
    "OAUTH ROUTE": "OAUTH ルート",
    "ChatGPT account usage": "ChatGPT アカウント使用量",
    "Measured by this router": "このルーターで計測",
    "Not reported by provider": "プロバイダーからの報告なし",
    "Thinking · %@": "思考中 · %@",
    "ROUTER": "ルーター",
    "QUOTAS": "割り当て",
    "Connect a provider to see its quota here.": "プロバイダーを接続すると、ここに割り当てが表示されます。",
    "DAILY TOKENS": "日次トークン",
    "resets soon": "まもなくリセット",
    "Download anyway?": "このままダウンロードしますか？",
    "local model": "ローカルモデル",
    "none installed": "未インストール",
    "installed": "インストール済み",
    "ON THIS MAC": "この Mac",
    "MODEL": "モデル",
    "SIZE": "サイズ",
    "QUICK PICKS": "クイック選択",
    "shortlist for this Mac": "この Mac 向けの厳選リスト",
    "CODING": "コーディング",
    "IMAGE READING": "画像読み取り",
    "DISCOVER OLLAMA": "Ollama を発見",
    "cloud-only": "クラウドのみ",
    "Size tags choose the model scale. Q4/Q8/BF16 are weight precision; MLX/NVFP4 are hardware-oriented builds; cloud tags run remotely. Codex compatibility is checked only after a pull.": "サイズタグはモデルの規模を選択します。Q4/Q8/BF16 は重みの精度、MLX/NVFP4 はハードウェア向けビルド、クラウドタグはリモートで実行されます。Codex 互換性はプル後にのみ確認されます。",
    "Search family or tag": "ファミリーまたはタグを検索",
    "INSTALL A MODEL": "モデルをインストール",
    "Ollama tag or URL": "Ollama のタグまたは URL",
    "Use a tag or model-page URL. Downloads stay headless.": "タグまたはモデルページの URL を入力してください。ダウンロードはバックグラウンドで行われます。",
    "gemma4:12b or ollama.com/library/gemma4:12b": "gemma4:12b または ollama.com/library/gemma4:12b",
    "BEST FIT FOR THIS MAC": "この Mac に最適",
    "CLOUD ONLY · NO LOCAL DOWNLOAD": "クラウドのみ · ローカルダウンロードなし",
    "NO LOCAL VARIANT FITS THIS MAC": "この Mac に適合するローカル版なし",
    "managed": "管理対象",
    "not started": "未起動",
    "Models:": "モデル：",
    "Update Ollama": "Ollama をアップデート",
    "cloud": "クラウド",
    "won't fit": "収まらない",
    "cloud only": "クラウドのみ",
    "Anyway": "このままダウンロード",
    "Default": "デフォルト",
    "Cloud": "クラウド",
    "Apple Silicon build": "Apple Silicon ビルド",
    "NVFP4 build": "NVFP4 ビルド",
    "4-bit build": "4 ビットビルド",
    "8-bit build": "8 ビットビルド",
    "BF16 build": "BF16 ビルド",
    "Coding build": "コーディングビルド",
    "Specialized build": "特化型ビルド",
    "BEST FIT": "最適",
    "CLOUD": "クラウド",
    "DEFAULT": "デフォルト",
    "TIGHT": "メモリぎりぎり",
    "WON'T FIT": "収まらない",
    "memory tight": "メモリぎりぎり",
    "verified": "検証済み",
    "untested": "未テスト",
    "accurate": "正確",
    "inaccurate": "不正確",
    "tight": "ぎりぎり",
    "too-large": "大きすぎ",
    "good": "適合",
    "tags": "タグ",
    "fit": "適合",
    "none fit": "適合なし",
    "Local model": "ローカルモデル",
    "Installing": "インストール中",
    "testing…": "テスト中…",
    "Actions for %@": "%@ の操作",
    "speed unmeasured": "速度未測定",
    "vision only — no tools": "ビジョンのみ — ツール非対応",
    "Downloading": "ダウンロード中",
    "Last download failed": "前回のダウンロードに失敗しました",
    "ChatGPT subscription": "ChatGPT サブスクリプション",
    "measured on this Mac": "この Mac で計測",
    "tokens": "トークン",
    "requests": "リクエスト",
    "All good": "すべて正常",
    "Router ready": "ルーター準備完了",
    "Current limit": "現在の上限",
    "Daily limit": "日次上限",
    "Weekly limit": "週間上限",
    "Monthly limit": "月間上限",
    "5-hour limit": "5 時間の上限",
    "Hidden from picker — show it below to use it here": "ピッカーから非表示 — ここで使用するには下で表示してください",
    "Apply the checked-out router revision, then run the Codex doctor": "チェックアウト済みのルーターリビジョンを適用してから Codex doctor を実行",
    "Run the Codex doctor and repair managed router files": "Codex doctor を実行し、管理対象のルーターファイルを修復",
    "Sign in or paste an API key": "サインインするか API キーを貼り付けてください",
    "required": "必須",
    "Checking…": "確認中…",
    "Reading via": "読み取りエンジン",
    "Off — text-only models refuse pasted images": "オフ — テキスト専用モデルは貼り付けた画像を読み取れません",
    "Daily token usage line chart": "日次トークン使用量の折れ線グラフ",
    "agent": "エージェント",
    "agents": "エージェント",
    "Active": "アクティブ",
    "Low": "低",
    "Medium": "中",
    "High": "高",
    "Model provider": "モデルプロバイダー",
    "Resets": "リセット時刻",
    "Menu bar mode": "メニューバーモード",
    "Standard": "標準",
    "Icon only": "アイコンのみ",
    "Compact icon only, no model name text": "コンパクトなアイコンのみ表示し、モデル名のテキストは非表示",
    "Show icon, model name, and usage": "アイコン、モデル名、使用量を表示",
    "Show model name": "モデル名を表示",
    "Current model or provider is visible in menu bar": "現在のモデルまたはプロバイダーをメニューバーに表示",
    "Hide model name text in menu bar": "メニューバーにモデル名のテキストを表示しない",
    "Menu bar icon": "メニューバーアイコン",
    "Router mark": "ルーターマーク",
    "Provider icon": "プロバイダーアイコン",
    "Activity dot": "アクティビティドット",
    "Preset icon": "プリセットアイコン",
    "Custom image": "カスタム画像",
    "Choose the icon displayed in the menu bar": "メニューバーに表示するアイコンを選択",
    "Choose Image…": "画像を選択…",
    "No custom image selected": "カスタム画像は未選択",
    "Custom image missing": "カスタム画像が見つかりません",
    "Codex Router · %@ (%@) · %@": "Codex Router · %@ (%@) · %@",
    "Codex Router · %@ (%@)": "Codex Router · %@ (%@)",
    "Select": "選択",
    "Service health": "サービスの状態",
    "Checking": "確認中",
    "All clear": "問題ありません",
    "Serving locally": "ローカルで稼働中",
    "Degraded": "低下",
    "Offline": "オフライン",
    "Health endpoint unavailable": "ヘルスエンドポイントを利用できません",
    "Unknown": "不明",
    "Waiting for health report": "ヘルスレポートを待機中",
    "Standby": "待機中",
    "Not enabled": "有効になっていません",
    "Unreachable": "到達不能",
    "Reachable": "到達可能",
    "External forwarders": "外部フォワーダー",
    "Subagent": "サブエージェント",
    "thinking": "思考",

    // Provider catalogs: the on-demand panel that asks a configured
    // provider for its current model list and curates from it.
    "Provider catalogs": "プロバイダーカタログ",
    "Load the latest provider models": "プロバイダーの最新モデルを読み込む",
    "Connect a supported provider to load its latest models.": "対応プロバイダーを接続すると最新モデルを読み込めます。",
    "Load models asks that provider for its current list. Choosing models adds them to the router and republishes every installed client.": "「モデルを読み込む」はプロバイダーに現在の一覧を問い合わせます。モデルを選ぶとルーターに追加され、インストール済みのすべてのクライアントが再発行されます。",
    "Reload provider models": "プロバイダーモデルを再読み込み",
    "Reloading provider models…": "プロバイダーモデルを再読み込み中…",
    "Fetch the current catalog from every connected provider that supports live model discovery.": "ライブのモデル探索に対応する接続済みプロバイダーすべてから現在のカタログを取得します。",
    "Refresh models": "モデルを更新",
    "Reload installed and available local models from the router.": "ルーターからインストール済みおよび利用可能なローカルモデルを再読み込みします。",
    "Loading models": "モデルを読み込み中",
    "Search available models": "利用可能なモデルを検索",
    "No provider models match this search.": "この検索に一致するプロバイダーモデルはありません。",
    "Search providers": "プロバイダーを検索",
    "No providers match this search.": "この検索に一致するプロバイダーはありません。",
    "Search subagent models": "サブエージェントモデルを検索",
    "No subagent models match this search.": "この検索に一致するサブエージェントモデルはありません。",
    "Clear search": "検索をクリア",
    "Added": "追加済み",
    "Showing the first 80 matches. Search to narrow the list.": "最初の 80 件の一致のみ表示しています。検索して絞り込んでください。",
    "%d selected": "%d 件選択中",
    "Add selected": "選択項目を追加",
    "Load the current list from this provider.": "このプロバイダーから現在の一覧を読み込みます。",
    "saved list": "保存済みの一覧",
    "live list": "最新の一覧",
    "%d models · %d added · %@": "%d 個のモデル · %d 個追加済み · %@",
  ]
}
