/// Korean translations for strings rendered by the native tray and
/// Dynamic Island. English source text is the key; see Localization.swift.
enum RouterKoreanText {
  static let values: [String: String] = [
    "Uninstalling": "제거 중",
    "Off by default · compacts old results; RTK shapes routed compaction": "기본적으로 꺼짐 · 오래된 결과를 압축하고 RTK가 라우팅 압축을 정리합니다",
    "Fix Codex Router installation": "Codex 라우터 설치 복구",
    "Language": "언어",
    "System": "시스템 따름",
    "Tray language. Reopen the panel to apply everywhere.": "트레이 언어입니다. 패널을 다시 열면 전체에 적용됩니다.",
    "Usage and activity over the notch on every display": "모든 디스플레이의 노치 위에 사용량과 활동 표시",
    "Off by default. The menu-bar panel stays available either way.": "기본적으로 꺼짐. 메뉴 막대 패널은 어느 경우든 계속 사용할 수 있습니다.",
    "Idle": "대기",
    "LOCAL FALLBACK": "로컬 폴백",
    "local fallback": "로컬 폴백",
    "%d local fallback dates": "로컬 폴백 날짜 %d일",
    "1 local fallback date": "로컬 폴백 날짜 1일",
    "OpenAI account usage; missing dates use local router fallback": "OpenAI 계정 사용량. 누락된 날짜는 로컬 라우터 폴백을 사용합니다",
    "OpenAI supplied no account bucket for these dates; local router traffic fills the gap. These are not global account totals.": "OpenAI가 해당 날짜의 계정 버킷을 제공하지 않아 로컬 라우터 트래픽으로 보완합니다. 전역 계정 합계가 아닙니다.",
    "Thinking": "생각 중",
    "Starting": "시작 중",
    "Error": "오류",
    "Codex subscription": "Codex 구독",
    "%@ left": "%@ 남음",
    "%d chats": "채팅 %d개",
    "Active session": "활성 세션",
    "No traffic": "트래픽 없음",
    "Ready to enable": "활성화 준비 완료",
    "Needs setup": "설정 필요",
    "OAuth · enabled": "OAuth · 활성화됨",
    "API · enabled": "API · 활성화됨",
    "Always": "항상 표시",
    "With Codex": "Codex와 함께 표시",
    "Off": "끔",
    "Notch": "노치",
    "Desktop": "데스크톱",
    "Usage": "사용량",
    "Usage and live activity": "사용량 및 실시간 활동",
    "Status": "상태",
    "Settings": "설정",
    "Control Center": "제어 센터",
    "Codex Router": "Codex Router",
    "Updated": "업데이트됨",
    "None": "없음",
    "none": "없음",
    "Local": "로컬",
    "Auto": "자동",
    "Codex account": "Codex 계정",
    "ChatGPT %@": "ChatGPT %@",
    "ChatGPT limit": "ChatGPT 한도",
    "Current usage": "현재 사용량",
    "All usage": "전체 사용량",
    "7-day snapshot": "최근 7일 스냅샷",
    "Tokens by model": "모델별 토큰",
    "Router": "라우터",
    "Model speed": "모델 속도",
    "Live requests": "실시간 요청",
    "Quota resets": "할당량 초기화",
    "No traffic right now": "현재 트래픽이 없습니다",
    "Ready for the next request": "다음 요청을 받을 준비가 되었습니다",
    "No model observed": "아직 관측된 모델이 없습니다",
    "No usage recorded yet": "아직 기록된 사용량이 없습니다",
    "Waiting": "대기 중",
    "No samples": "샘플 없음",
    "Appears after a metered reply": "측정된 응답 이후에 표시됩니다",
    "Observed output throughput": "관측된 출력 속도",
    "Nothing in flight": "진행 중인 요청 없음",
    "no tools — can't chat": "도구 없음 — 채팅 불가",
    "works in Codex": "Codex에서 작동",
    "unreliable in Codex": "Codex에서 불안정",
    "not offered yet": "아직 제공되지 않음",
    "fails in Codex": "Codex에서 실패",
    "chat — untested": "채팅 — 테스트되지 않음",
    "Provider added. Restart Codex to refresh its model picker.": "제공업체가 추가되었습니다. 모델 선택기를 새로 고치려면 Codex를 재시작하세요.",
    "Provider hidden. Restart Codex to refresh its model picker.": "제공업체가 숨겨졌습니다. 모델 선택기를 새로 고치려면 Codex를 재시작하세요.",
    "Show tray": "트레이 아이콘 표시",
    "Appears with Codex or ChatGPT, hides when they quit": "Codex 또는 ChatGPT 실행 시 표시되고 종료하면 숨겨집니다",
    "Kept on: a terminal session has no window to follow": "항상 켜짐: 터미널 세션에는 따라갈 창이 없습니다",
    "DeepSeek Harness": "DeepSeek Harness",
    "Install DeepSeek Harness and publish this router's models into it": "DeepSeek Harness를 설치하고 이 라우터의 모델을 게시합니다",
    "Not installed · installs the CLI, then publishes this router's models": "설치되지 않음 · CLI를 설치한 뒤 이 라우터의 모델을 게시합니다",
    "Needs Node %@ or newer; this router runs Node %@": "Node %@ 이상이 필요합니다. 이 라우터는 Node %@에서 실행 중입니다",
    "%@ · routed models published · `dsh web` to start": "%@ · 라우팅된 모델 게시됨 · `dsh web`으로 시작",
    "%@ · installed but not routed here yet": "%@ · 설치되었지만 아직 이 라우터에 연결되지 않음",
    "%d models published. Run `%@` to start.": "모델 %d개가 게시되었습니다. `%@`을(를) 실행해 시작하세요.",
    "Installing DeepSeek Harness…": "DeepSeek Harness 설치 중…",
    "Publishing routed models…": "라우팅된 모델 게시 중…",
    "Setting up DeepSeek Harness": "DeepSeek Harness 설정 중",
    "Connect": "연결",
    "Open site": "사이트 열기",
    "Turn off": "끄기",
    "Disconnect": "연결 해제",
    "Stopping…": "중지 중…",
    "Stopped. Memory and CPU released.": "중지되었습니다. 메모리와 CPU가 해제되었습니다.",
    "This harness was started outside the router — stop it where you started it.": "이 Harness는 라우터 외부에서 시작되었습니다 — 시작한 위치에서 중지하세요.",
    "Stop the harness process and free its memory and CPU": "Harness 프로세스를 중지하고 메모리와 CPU를 해제합니다",
    "Disconnecting…": "연결 해제 중…",
    "Turned off. The harness and its own settings were kept.": "꺼졌습니다. Harness와 자체 설정은 유지되었습니다.",
    "Remove this router's models from the harness, keeping the harness itself": "Harness에서 이 라우터의 모델을 제거하되 Harness 자체는 유지합니다",
    "Start": "시작",
    "Open the DeepSeek Harness browser UI": "DeepSeek Harness 브라우저 UI 열기",
    "Start the DeepSeek Harness browser UI": "DeepSeek Harness 브라우저 UI 시작",
    "Starting DeepSeek Harness…": "DeepSeek Harness 시작 중…",
    "%@ · running at %@": "%@ · %@에서 실행 중",
    "%@ · routed models published · not running": "%@ · 라우팅된 모델 게시됨 · 실행 중 아님",
    "%d models published. Press play to open the harness.": "모델 %d개가 게시되었습니다. 재생 버튼을 눌러 Harness를 여세요.",
    "%d models published, but the harness UI did not start: %@": "모델 %d개가 게시되었지만 Harness UI가 시작되지 않았습니다: %@",
    "Menu bar icon stays visible": "메뉴 막대 아이콘 항상 표시",
    "Dynamic Island": "다이내믹 아일랜드",
    "Quotas and live activity pinned to the desktop": "할당량과 실시간 활동을 데스크톱에 고정",
    "Show provider usage and activity status": "제공업체 사용량과 활동 상태 표시",
    "Use Router with ChatGPT": "ChatGPT에서 라우터 사용",
    "Share ChatGPT subscription": "ChatGPT 구독 공유",
    "Sharing status unavailable": "공유 상태를 확인할 수 없음",
    "Sharing enabled": "공유가 활성화됨",
    "Sharing disabled": "공유가 비활성화됨",
    "login usable · about %@h left": "로그인 사용 가능 · 약 %@시간 남음",
    "login usable": "로그인 사용 가능",
    "login expired": "로그인 만료됨",
    "login unavailable · sign-in data detected": "로그인 사용 불가 · 로그인 데이터 감지됨",
    "login unavailable · run codex login": "로그인 사용 불가 · codex login 실행 필요",
    "Enable ChatGPT session sharing?": "ChatGPT 세션 공유를 활성화할까요?",
    "Enabling lets other local Codex Router clients spend this user's ChatGPT subscription. Only continue for clients you trust on this Mac.": "활성화하면 다른 로컬 Codex Router 클라이언트가 이 사용자의 ChatGPT 구독을 사용할 수 있습니다. 이 Mac에서 신뢰하는 클라이언트에만 계속 진행하세요.",
    "Enable sharing": "공유 활성화",
    "A usable ChatGPT login is required before sharing can be enabled. Run codex login first.": "공유를 활성화하려면 사용 가능한 ChatGPT 로그인이 필요합니다. 먼저 codex login을 실행하세요.",
    "ChatGPT session-sharing status is unavailable. Refresh before changing it.": "ChatGPT 세션 공유 상태를 확인할 수 없습니다. 변경하기 전에 새로 고치세요.",
    "ChatGPT session sharing enabled for local router clients.": "로컬 라우터 클라이언트에 ChatGPT 세션 공유가 활성화되었습니다.",
    "ChatGPT session sharing disabled. Installed client catalogs were refreshed.": "ChatGPT 세션 공유를 비활성화하고 설치된 클라이언트 카탈로그를 새로 고쳤습니다.",
    "Native GPT + external models · task history preserved": "네이티브 GPT + 외부 모델 · 작업 기록 유지",
    "Keep ChatGPT login and the current task history": "ChatGPT 로그인과 현재 작업 기록 유지",
    "Use without OpenAI login": "OpenAI 로그인 없이 사용",
    "External providers · Codex restarts automatically": "외부 제공업체 · Codex가 자동으로 재시작됩니다",
    "Use connected models and restart Codex": "연결된 모델을 사용하고 Codex 재시작",
    "Token maxxing": "Token maxxing",
    "Forced off by CODEX_ROUTER_TOOL_RESULT_AGING=0": "CODEX_ROUTER_TOOL_RESULT_AGING=0에 의해 강제로 꺼짐",
    "External models · applies on the next request": "외부 모델 · 다음 요청부터 적용됩니다",
    "Providers": "제공업체",
    "Auto-saved": "자동 저장됨",
    "Applying…": "적용 중…",
    "Subagent models": "서브에이전트 모델",
    "All proven models": "모든 검증된 모델",
    "Model picker": "모델 선택기",
    "Local LLMs": "로컬 LLM",
    "Vision": "비전",
    "Subagent choices do not hide models from Codex's picker — use Model picker below for that.": "서브에이전트 선택은 Codex 선택기에서 모델을 숨기지 않습니다 — 숨기려면 아래의 모델 선택기를 사용하세요.",
    "Hidden models stay connected but are not offered by Codex.": "숨긴 모델은 계속 연결되어 있지만 Codex에는 제공되지 않습니다.",
    "Run models locally through Ollama. Enable an installed model to make it available to Codex.": "Ollama를 통해 모델을 로컬에서 실행합니다. 설치된 모델을 활성화하면 Codex에서 사용할 수 있습니다.",
    "Run local models through Ollama or the curated MLX runtime. Installed models are wired into the same Codex proxy.": "Ollama 또는 선별된 MLX 런타임으로 로컬 모델을 실행합니다. 설치된 모델은 동일한 Codex 프록시에 연결됩니다.",
    "Nothing installed yet. Start with a quick pick or browse the Ollama catalog below.": "아직 설치된 모델이 없습니다. 빠른 선택으로 시작하거나 아래 Ollama 카탈로그를 둘러보세요.",
    "Install a model": "모델 설치",
    "Install": "설치",
    "Clear": "지우기",
    "Download": "다운로드",
    "Cancel": "취소",
    "Confirm": "확인",
    "Confirm removal?": "제거하시겠습니까?",
    "Remove model": "모델 제거",
    "Measure speed": "속도 측정",
    "Test image reading": "이미지 읽기 테스트",
    "Use for image reading": "이미지 읽기에 사용",
    "Reading images": "이미지 읽기",
    "loaded": "로드됨",
    "Installing local model": "로컬 모델 설치 중",
    "Local model ready": "로컬 모델 준비 완료",
    "Local model install failed": "로컬 모델 설치 실패",
    "Text-only models can't see images. When on, a vision model reads the paste and hands over the text.": "텍스트 전용 모델은 이미지를 볼 수 없습니다. 켜면 비전 모델이 붙여넣은 내용을 읽고 텍스트를 전달합니다.",
    "Read images for text-only models": "텍스트 전용 모델을 위한 이미지 읽기",
    "Engine": "엔진",
    "Paid (cloud)": "유료(클라우드)",
    "Your ChatGPT plan": "내 ChatGPT 요금제",
    "Cannot run subagents": "서브에이전트를 실행할 수 없음",
    "Effort as subagent": "서브에이전트 추론 강도",
    "Model default": "모델 기본값",
    "Update": "업데이트",
    "Fix": "복구",
    "Working…": "작업 중…",
    "Update or fix failed": "업데이트 또는 복구 실패",
    "Router unavailable": "라우터 사용 불가",
    "Run setup, then refresh this panel.": "설정을 실행한 뒤 이 패널을 새로 고치세요.",
    "Refresh": "새로 고침",
    "Refreshing…": "새로 고치는 중…",
    "%d accounts": "계정 %d개",
    "1 account": "계정 1개",
    "Restart": "재시작",
    "Restarting…": "재시작 중…",
    "Restart failed: %@": "재시작 실패: %@",
    "Restarted without updating: %@": "업데이트 없이 재시작되었습니다: %@",
    "Awaiting data": "데이터 대기 중",
    "Quit": "종료",
    "API key": "API 키",
    "Replacement %@": "교체할 %@",
    "Paste %@": "%@ 붙여넣기",
    "Click the check again to delete this credential": "이 자격 증명을 삭제하려면 체크 표시를 다시 클릭하세요",
    "Checking setup…": "설정 확인 중…",
    "Session expired · reconnect for account usage": "세션 만료됨 · 계정 사용량을 보려면 다시 연결하세요",
    "Official CLI required": "공식 CLI 필요",
    "Sign in with the official CLI": "공식 CLI로 로그인",
    "Operator-owned Google OAuth client required": "운영자 소유 Google OAuth 클라이언트 필요",
    "Live test required · sends a small prompt and uses quota": "라이브 테스트 필요 · 짧은 프롬프트를 전송하며 할당량을 사용합니다",
    "Disconnect the incompatible router record before signing in": "호환되지 않는 라우터 자격 증명을 연결 해제한 후 로그인하세요",
    "Setup required": "설정 필요",
    "Reconnect": "다시 연결",
    "Reconnect OAuth": "OAuth 다시 연결",
    "Open browser sign-in": "브라우저 로그인 열기",
    "Finish sign-in in browser": "브라우저에서 로그인 완료",
    "OAuth sessions refresh automatically. Reconnect opens browser sign-in when approval is required.": "OAuth 세션은 자동으로 갱신됩니다. 재승인이 필요하면 다시 연결을 눌러 브라우저 로그인을 여세요.",
    "Install & Sign In": "설치 후 로그인",
    "Sign In": "로그인",
    "Install the official CLI and sign in": "공식 CLI를 설치하고 로그인하세요",
    "Sign in again with the official CLI": "공식 CLI로 다시 로그인하세요",
    "Cancel credential replacement": "자격 증명 교체 취소",
    "Click again to delete the stored credential": "저장된 자격 증명을 삭제하려면 다시 클릭하세요",
    "Remove stored OAuth client and session": "저장된 OAuth 클라이언트 및 세션 제거",
    "Test & Enable": "테스트 후 활성화",
    "Remove stored %@": "저장된 %@ 제거",
    "Available in Codex": "Codex에서 사용 가능",
    "Hidden from Codex": "Codex에서 숨겨짐",
    "Signed in": "로그인됨",
    "Add Key": "키 추가",
    "Save": "저장",
    "Open usage dashboard": "사용량 대시보드 열기",
    "Daily token usage": "일별 토큰 사용량",
    "Full": "전체",
    "Full token numbers": "전체 토큰 수",
    "Millions of tokens": "백만 토큰 단위",
    "Token unit": "토큰 단위",
    "Router traffic": "라우터 트래픽",
    "Loading provider usage…": "제공업체 사용량 불러오는 중…",
    "Loading native Codex usage…": "네이티브 Codex 사용량 불러오는 중…",
    "Set up this provider below to fetch its account usage.": "계정 사용량을 가져오려면 아래에서 이 제공업체를 설정하세요.",
    "Usage limit": "사용량 한도",
    "No reset reported": "초기화 시각이 보고되지 않음",
    "Reconnect below": "아래에서 다시 연결하세요",
    "OAuth expired · reconnect below": "OAuth 만료됨 · 아래에서 다시 연결하세요",
    "No router traffic yet": "아직 라우터 트래픽이 없습니다",
    "Configured · currently hidden": "구성됨 · 현재 숨겨짐",
    "Sign in again to restore quota": "할당량을 복원하려면 다시 로그인하세요",
    "Local router traffic": "로컬 라우터 트래픽",
    "What do these tags mean?": "이 태그들은 무슨 뜻인가요?",
    "Hide tag guide": "태그 안내 숨기기",
    "Show fewer tags": "태그 접기",
    "View all %@ tags": "태그 %@개 모두 보기",
    "Hide machine & runtime": "기기 및 런타임 숨기기",
    "Machine & runtime": "기기 및 런타임",
    "Show fewer quick picks": "빠른 선택 접기",
    "View more quick picks": "빠른 선택 더 보기",
    "Show all": "모두 표시",
    "Hide all": "모두 숨기기",
    "Update and verify Codex Router": "Codex 라우터 업데이트 및 검증",
    "Running Codex Router maintenance": "Codex 라우터 유지 관리 실행 중",
    "Daily token usage chart. Hover a day for its displayed token count.": "일별 토큰 사용량 차트입니다. 날짜 위에 마우스를 올리면 표시된 토큰 수를 볼 수 있습니다.",
    "Show %@ usage": "%@ 사용량 표시",
    "WEEKLY LEFT": "주간 잔여",
    "TODAY TOKENS": "오늘 토큰",
    "DAILY USAGE": "일별 사용량",
    "LAST 7 DAYS": "최근 7일",
    "Collapse": "접기",
    "TODAY'S TOKENS": "오늘 토큰",
    "DAILY TOKEN TREND": "일별 토큰 추이",
    "ACTIVE NOW": "현재 활동",
    "ACTIVE PROVIDER": "현재 제공업체",
    "USED": "사용됨",
    "Account and traffic are provider-scoped": "계정과 트래픽은 제공업체별로 구분됩니다",
    "Live": "실시간",
    "Last used": "마지막 사용",
    "Running chats": "실행 중인 채팅",
    "Router overview": "라우터 개요",
    "Ready": "준비 완료",
    "CHATGPT • NATIVE": "CHATGPT · 네이티브",
    "XAI • OAUTH SESSION": "XAI · OAUTH 세션",
    "XAI • METERED API": "XAI · 종량제 API",
    "METERED API": "종량제 API",
    "OAUTH ROUTE": "OAUTH 경로",
    "ChatGPT account usage": "ChatGPT 계정 사용량",
    "Measured by this router": "이 라우터에서 측정됨",
    "Not reported by provider": "제공업체가 보고하지 않음",
    "Thinking · %@": "생각 중 · %@",
    "ROUTER": "라우터",
    "QUOTAS": "할당량",
    "Connect a provider to see its quota here.": "제공업체를 연결하면 여기에서 할당량을 볼 수 있습니다.",
    "DAILY TOKENS": "일별 토큰",
    "resets soon": "곧 초기화",
    "Download anyway?": "그래도 다운로드할까요?",
    "local model": "로컬 모델",
    "none installed": "설치된 항목 없음",
    "installed": "설치됨",
    "ON THIS MAC": "이 Mac",
    "MODEL": "모델",
    "SIZE": "크기",
    "QUICK PICKS": "빠른 선택",
    "shortlist for this Mac": "이 Mac에 적합한 추천 목록",
    "CODING": "코딩",
    "IMAGE READING": "이미지 읽기",
    "DISCOVER OLLAMA": "OLLAMA 둘러보기",
    "cloud-only": "클라우드 전용",
    "Size tags choose the model scale. Q4/Q8/BF16 are weight precision; MLX/NVFP4 are hardware-oriented builds; cloud tags run remotely. Codex compatibility is checked only after a pull.": "크기 태그는 모델 규모를 선택합니다. Q4/Q8/BF16은 가중치 정밀도이고 MLX/NVFP4는 하드웨어 지향 빌드이며 클라우드 태그는 원격으로 실행됩니다. Codex 호환성은 모델을 받은 후에만 확인됩니다.",
    "Search family or tag": "계열 또는 태그 검색",
    "INSTALL A MODEL": "모델 설치",
    "Ollama tag or URL": "Ollama 태그 또는 URL",
    "Use a tag or model-page URL. Downloads stay headless.": "태그 또는 모델 페이지 URL을 사용하세요. 다운로드는 백그라운드에서 진행됩니다.",
    "gemma4:12b or ollama.com/library/gemma4:12b": "gemma4:12b 또는 ollama.com/library/gemma4:12b",
    "BEST FIT FOR THIS MAC": "이 Mac에 최적",
    "CLOUD ONLY · NO LOCAL DOWNLOAD": "클라우드 전용 · 로컬 다운로드 없음",
    "NO LOCAL VARIANT FITS THIS MAC": "이 Mac에 맞는 로컬 변형 없음",
    "managed": "관리됨",
    "not started": "시작되지 않음",
    "Models:": "모델:",
    "Update Ollama": "Ollama 업데이트",
    "cloud": "클라우드",
    "won't fit": "맞지 않음",
    "cloud only": "클라우드 전용",
    "Anyway": "그래도 다운로드",
    "Default": "기본",
    "Cloud": "클라우드",
    "Apple Silicon build": "Apple Silicon 빌드",
    "NVFP4 build": "NVFP4 빌드",
    "4-bit build": "4비트 빌드",
    "8-bit build": "8비트 빌드",
    "BF16 build": "BF16 빌드",
    "Coding build": "코딩 빌드",
    "Specialized build": "특화 빌드",
    "BEST FIT": "최적",
    "CLOUD": "클라우드",
    "DEFAULT": "기본",
    "TIGHT": "메모리 빠듯",
    "WON'T FIT": "맞지 않음",
    "memory tight": "메모리 빠듯",
    "verified": "검증됨",
    "untested": "테스트되지 않음",
    "accurate": "정확",
    "inaccurate": "부정확",
    "tight": "빠듯함",
    "too-large": "너무 큼",
    "good": "적합",
    "tags": "태그",
    "fit": "맞음",
    "none fit": "맞는 항목 없음",
    "Local model": "로컬 모델",
    "Installing": "설치 중",
    "testing…": "테스트 중…",
    "Actions for %@": "%@ 작업",
    "speed unmeasured": "속도 미측정",
    "vision only — no tools": "비전 전용 — 도구 미지원",
    "Downloading": "다운로드 중",
    "Last download failed": "마지막 다운로드 실패",
    "ChatGPT subscription": "ChatGPT 구독",
    "measured on this Mac": "이 Mac에서 측정됨",
    "tokens": "토큰",
    "requests": "요청",
    "All good": "모두 정상",
    "Router ready": "라우터 준비 완료",
    "Current limit": "현재 한도",
    "Daily limit": "일간 한도",
    "Weekly limit": "주간 한도",
    "Monthly limit": "월간 한도",
    "5-hour limit": "5시간 한도",
    "Hidden from picker — show it below to use it here": "선택기에서 숨겨짐 — 여기서 사용하려면 아래에서 표시하세요",
    "Apply the checked-out router revision, then run the Codex doctor": "체크아웃된 라우터 리비전을 적용한 뒤 Codex doctor를 실행합니다",
    "Run the Codex doctor and repair managed router files": "Codex doctor를 실행하고 관리되는 라우터 파일을 복구합니다",
    "Sign in or paste an API key": "로그인하거나 API 키를 붙여넣으세요",
    "required": "필수",
    "Checking…": "확인 중…",
    "Reading via": "읽기 엔진",
    "Off — text-only models refuse pasted images": "꺼짐 — 텍스트 전용 모델은 붙여넣은 이미지를 읽을 수 없습니다",
    "Daily token usage line chart": "일별 토큰 사용량 선 그래프",
    "agent": "에이전트",
    "agents": "에이전트",
    "Active": "활동 중",
    "Low": "낮음",
    "Medium": "중간",
    "High": "높음",
    "Model provider": "모델 제공업체",
    "Resets": "초기화",
    "Menu bar mode": "메뉴 막대 모드",
    "Standard": "표준",
    "Icon only": "아이콘만",
    "Compact icon only, no model name text": "컴팩트 아이콘만 표시, 모델 이름 텍스트 숨김",
    "Show icon, model name, and usage": "아이콘, 모델 이름 및 사용량 표시",
    "Show model name": "모델 이름 표시",
    "Current model or provider is visible in menu bar": "현재 모델 또는 제공업체가 메뉴 막대에 표시됩니다",
    "Hide model name text in menu bar": "메뉴 막대에서 모델 이름 텍스트 숨기기",
    "Menu bar icon": "메뉴 막대 아이콘",
    "Router mark": "라우터 마크",
    "Provider icon": "제공업체 아이콘",
    "Activity dot": "활동 점",
    "Preset icon": "프리셋 아이콘",
    "Custom image": "사용자 지정 이미지",
    "Choose the icon displayed in the menu bar": "메뉴 막대에 표시할 아이콘 선택",
    "Choose Image…": "이미지 선택…",
    "No custom image selected": "선택된 사용자 지정 이미지 없음",
    "Custom image missing": "사용자 지정 이미지가 없습니다",
    "Codex Router · %@ (%@) · %@": "Codex Router · %@ (%@) · %@",
    "Codex Router · %@ (%@)": "Codex Router · %@ (%@)",
    "Select": "선택",
    "Service health": "서비스 상태",
    "Checking": "확인 중",
    "All clear": "모두 정상",
    "Serving locally": "로컬에서 서비스 중",
    "Degraded": "성능 저하",
    "Offline": "오프라인",
    "Health endpoint unavailable": "상태 확인 엔드포인트를 사용할 수 없습니다",
    "Unknown": "알 수 없음",
    "Waiting for health report": "상태 보고서를 기다리는 중",
    "Standby": "대기",
    "Not enabled": "활성화되지 않음",
    "Unreachable": "연결할 수 없음",
    "Reachable": "연결 가능",
    "External forwarders": "외부 포워더",
    "Subagent": "서브에이전트",
    "thinking": "추론",

    // Provider catalogs: the on-demand panel that asks a configured
    // provider for its current model list and curates from it.
    "Provider catalogs": "제공자 카탈로그",
    "Load the latest provider models": "제공자의 최신 모델 불러오기",
    "Connect a supported provider to load its latest models.": "지원되는 제공자를 연결하면 최신 모델을 불러올 수 있습니다.",
    "Load models asks that provider for its current list. Choosing models adds them to the router and republishes every installed client.": "\"모델 불러오기\"는 해당 제공자에게 현재 목록을 요청합니다. 모델을 선택하면 라우터에 추가되고 설치된 모든 클라이언트가 다시 게시됩니다.",
    "Reload provider models": "제공자 모델 다시 불러오기",
    "Reloading provider models…": "제공자 모델을 다시 불러오는 중…",
    "Fetch the current catalog from every connected provider that supports live model discovery.": "실시간 모델 검색을 지원하는 연결된 모든 제공자에서 현재 카탈로그를 가져옵니다.",
    "Refresh models": "모델 새로 고침",
    "Reload installed and available local models from the router.": "라우터에서 설치된 로컬 모델과 사용 가능한 로컬 모델을 다시 불러옵니다.",
    "Loading models": "모델 불러오는 중",
    "Search available models": "사용 가능한 모델 검색",
    "No provider models match this search.": "이 검색과 일치하는 제공자 모델이 없습니다.",
    "Search providers": "제공자 검색",
    "No providers match this search.": "이 검색과 일치하는 제공자가 없습니다.",
    "Search subagent models": "서브에이전트 모델 검색",
    "No subagent models match this search.": "이 검색과 일치하는 서브에이전트 모델이 없습니다.",
    "Clear search": "검색 지우기",
    "Added": "추가됨",
    "Showing the first 80 matches. Search to narrow the list.": "일치하는 항목 중 처음 80개만 표시합니다. 검색해 목록을 좁히세요.",
    "%d selected": "%d개 선택됨",
    "Add selected": "선택 항목 추가",
    "Load the current list from this provider.": "이 제공자에서 현재 목록을 불러옵니다.",
    "saved list": "저장된 목록",
    "live list": "실시간 목록",
    "%d models · %d added · %@": "모델 %d개 · %d개 추가됨 · %@",
  ]
}
