/// Hindi translations for strings rendered by the native tray and
/// Dynamic Island. English source text is the key; see Localization.swift.
enum RouterHindiText {
  static let values: [String: String] = [
    "Uninstalling": "अनइंस्टॉल हो रहा है",
    "Off by default · compacts old results; RTK shapes routed compaction": "डिफ़ॉल्ट रूप से बंद · पुराने परिणाम संपीड़ित करता है; RTK रूटेड संपीड़न को शेप करता है",
    "Fix Codex Router installation": "Codex राउटर इंस्टॉलेशन ठीक करें",
    "Language": "भाषा",
    "System": "सिस्टम के अनुसार",
    "Tray language. Reopen the panel to apply everywhere.": "ट्रे भाषा। हर जगह लागू करने के लिए पैनल फिर से खोलें।",
    "Usage and activity over the notch on every display": "हर डिस्प्ले पर नॉच के ऊपर उपयोग और गतिविधि",
    "Off by default. The menu-bar panel stays available either way.": "डिफ़ॉल्ट रूप से बंद। मेनू-बार पैनल किसी भी स्थिति में उपलब्ध रहता है।",
    "Idle": "निष्क्रिय",
    "LOCAL FALLBACK": "लोकल फ़ॉलबैक",
    "local fallback": "लोकल फ़ॉलबैक",
    "%d local fallback dates": "%d लोकल फ़ॉलबैक तारीखें",
    "1 local fallback date": "1 लोकल फ़ॉलबैक तारीख",
    "OpenAI account usage; missing dates use local router fallback": "OpenAI खाता उपयोग; गायब तारीखें लोकल राउटर फ़ॉलबैक उपयोग करती हैं",
    "OpenAI supplied no account bucket for these dates; local router traffic fills the gap. These are not global account totals.": "OpenAI ने इन तारीखों के लिए खाता बकेट नहीं दिए; लोकल राउटर ट्रैफ़िक उस कमी को भरता है। ये वैश्विक खाता कुल नहीं हैं।",
    "Thinking": "सोच रहा है",
    "Starting": "शुरू हो रहा है",
    "Error": "त्रुटि",
    "Codex subscription": "Codex सदस्यता",
    "%@ left": "%@ शेष",
    "%d chats": "%d चैट",
    "Active session": "सक्रिय सत्र",
    "No traffic": "कोई ट्रैफ़िक नहीं",
    "Ready to enable": "सक्षम करने के लिए तैयार",
    "Needs setup": "सेटअप आवश्यक",
    "OAuth · enabled": "OAuth · सक्षम",
    "API · enabled": "API · सक्षम",
    "Always": "हमेशा",
    "With Codex": "Codex के साथ",
    "Off": "बंद",
    "Notch": "नॉच",
    "Desktop": "डेस्कटॉप",
    "Usage": "उपयोग",
    "Usage and live activity": "उपयोग और लाइव गतिविधि",
    "Status": "स्थिति",
    "Settings": "सेटिंग्स",
    "Control Center": "नियंत्रण केंद्र",
    "Codex Router": "Codex Router",
    "Updated": "अपडेट हो गया",
    "None": "कोई नहीं",
    "none": "कोई नहीं",
    "Local": "स्थानीय",
    "Auto": "स्वचालित",
    "Codex account": "Codex खाता",
    "ChatGPT %@": "ChatGPT %@",
    "ChatGPT limit": "ChatGPT सीमा",
    "Current usage": "वर्तमान उपयोग",
    "All usage": "सारा उपयोग",
    "7-day snapshot": "7-दिवसीय स्नैपशॉट",
    "Tokens by model": "मॉडल के अनुसार टोकन",
    "Router": "राउटर",
    "Model speed": "मॉडल गति",
    "Live requests": "लाइव अनुरोध",
    "Quota resets": "कोटा रीसेट",
    "No traffic right now": "अभी कोई ट्रैफ़िक नहीं",
    "Ready for the next request": "अगले अनुरोध के लिए तैयार",
    "No model observed": "अभी तक कोई मॉडल नहीं देखा गया",
    "No usage recorded yet": "अभी तक कोई उपयोग दर्ज नहीं",
    "Waiting": "प्रतीक्षा में",
    "No samples": "कोई नमूना नहीं",
    "Appears after a metered reply": "मीटर की गई प्रतिक्रिया के बाद दिखाई देता है",
    "Observed output throughput": "देखी गई आउटपुट गति",
    "Nothing in flight": "अभी कोई अनुरोध प्रगति में नहीं",
    "no tools — can't chat": "कोई टूल नहीं — चैट नहीं हो सकती",
    "works in Codex": "Codex में काम करता है",
    "unreliable in Codex": "Codex में अविश्वसनीय",
    "not offered yet": "अभी उपलब्ध नहीं",
    "fails in Codex": "Codex में विफल",
    "chat — untested": "चैट — अपरीक्षित",
    "Provider added. Restart Codex to refresh its model picker.": "प्रदाता जोड़ा गया। मॉडल पिकर रीफ़्रेश करने के लिए Codex पुनः आरंभ करें।",
    "Provider hidden. Restart Codex to refresh its model picker.": "प्रदाता छिपा दिया गया। मॉडल पिकर रीफ़्रेश करने के लिए Codex पुनः आरंभ करें।",
    "Show tray": "ट्रे दिखाएँ",
    "Appears with Codex or ChatGPT, hides when they quit": "Codex या ChatGPT के साथ दिखाई देता है, उनके बंद होने पर छिप जाता है",
    "Kept on: a terminal session has no window to follow": "चालू रखा गया: टर्मिनल सत्र के पास अनुसरण करने के लिए कोई विंडो नहीं है",
    "DeepSeek Harness": "DeepSeek Harness",
    "Install DeepSeek Harness and publish this router's models into it": "DeepSeek Harness इंस्टॉल करें और इस राउटर के मॉडल उसमें प्रकाशित करें",
    "Not installed · installs the CLI, then publishes this router's models": "इंस्टॉल नहीं है · CLI इंस्टॉल करता है, फिर इस राउटर के मॉडल प्रकाशित करता है",
    "Needs Node %@ or newer; this router runs Node %@": "Node %@ या नया आवश्यक है; यह राउटर Node %@ पर चल रहा है",
    "%@ · routed models published · `dsh web` to start": "%@ · रूट किए गए मॉडल प्रकाशित · शुरू करने के लिए `dsh web`",
    "%@ · installed but not routed here yet": "%@ · इंस्टॉल है, लेकिन अभी यहाँ रूट नहीं हुआ",
    "%d models published. Run `%@` to start.": "%d मॉडल प्रकाशित हुए। शुरू करने के लिए `%@` चलाएँ।",
    "Installing DeepSeek Harness…": "DeepSeek Harness इंस्टॉल हो रहा है…",
    "Publishing routed models…": "रूट किए गए मॉडल प्रकाशित हो रहे हैं…",
    "Setting up DeepSeek Harness": "DeepSeek Harness सेट हो रहा है",
    "Connect": "कनेक्ट करें",
    "Open site": "साइट खोलें",
    "Turn off": "बंद करें",
    "Disconnect": "डिस्कनेक्ट करें",
    "Stopping…": "रुक रहा है…",
    "Stopped. Memory and CPU released.": "रुक गया। मेमोरी और CPU मुक्त हो गए।",
    "This harness was started outside the router — stop it where you started it.": "यह Harness राउटर के बाहर से शुरू किया गया था — इसे वहीं रोकें जहाँ से आपने शुरू किया था।",
    "Stop the harness process and free its memory and CPU": "Harness प्रक्रिया रोकें और उसकी मेमोरी व CPU मुक्त करें",
    "Disconnecting…": "डिस्कनेक्ट हो रहा है…",
    "Turned off. The harness and its own settings were kept.": "बंद कर दिया गया। Harness और उसकी अपनी सेटिंग्स रखी गई हैं।",
    "Remove this router's models from the harness, keeping the harness itself": "Harness से इस राउटर के मॉडल हटाएँ, Harness स्वयं बना रहे",
    "Start": "शुरू करें",
    "Open the DeepSeek Harness browser UI": "DeepSeek Harness ब्राउज़र UI खोलें",
    "Start the DeepSeek Harness browser UI": "DeepSeek Harness ब्राउज़र UI शुरू करें",
    "Starting DeepSeek Harness…": "DeepSeek Harness शुरू हो रहा है…",
    "%@ · running at %@": "%@ · %@ पर चल रहा है",
    "%@ · routed models published · not running": "%@ · रूट किए गए मॉडल प्रकाशित · नहीं चल रहा",
    "%d models published. Press play to open the harness.": "%d मॉडल प्रकाशित हुए। Harness खोलने के लिए प्ले दबाएँ।",
    "%d models published, but the harness UI did not start: %@": "%d मॉडल प्रकाशित हुए, लेकिन Harness UI शुरू नहीं हुआ: %@",
    "Menu bar icon stays visible": "मेनू बार आइकन दिखाई देता रहता है",
    "Dynamic Island": "डायनामिक आइलैंड",
    "Quotas and live activity pinned to the desktop": "कोटा और लाइव गतिविधि डेस्कटॉप पर पिन की गई",
    "Show provider usage and activity status": "प्रदाता उपयोग और गतिविधि स्थिति दिखाएँ",
    "Use Router with ChatGPT": "ChatGPT के साथ राउटर का उपयोग करें",
    "Share ChatGPT subscription": "ChatGPT सदस्यता साझा करें",
    "Sharing status unavailable": "साझाकरण स्थिति उपलब्ध नहीं है",
    "Sharing enabled": "साझाकरण चालू है",
    "Sharing disabled": "साझाकरण बंद है",
    "login usable · about %@h left": "लॉगिन उपयोग योग्य है · लगभग %@ घंटे शेष",
    "login usable": "लॉगिन उपयोग योग्य है",
    "login expired": "लॉगिन की अवधि समाप्त हो गई",
    "login unavailable · sign-in data detected": "लॉगिन उपलब्ध नहीं · साइन-इन डेटा मिला",
    "login unavailable · run codex login": "लॉगिन उपलब्ध नहीं · codex login चलाएँ",
    "Enable ChatGPT session sharing?": "ChatGPT सत्र साझाकरण चालू करें?",
    "Enabling lets other local Codex Router clients spend this user's ChatGPT subscription. Only continue for clients you trust on this Mac.": "इसे चालू करने पर अन्य स्थानीय Codex Router क्लाइंट इस उपयोगकर्ता की ChatGPT सदस्यता खर्च कर सकते हैं। केवल इस Mac के विश्वसनीय क्लाइंट के लिए आगे बढ़ें।",
    "Enable sharing": "साझाकरण चालू करें",
    "A usable ChatGPT login is required before sharing can be enabled. Run codex login first.": "साझाकरण चालू करने से पहले उपयोग योग्य ChatGPT लॉगिन आवश्यक है। पहले codex login चलाएँ।",
    "ChatGPT session-sharing status is unavailable. Refresh before changing it.": "ChatGPT सत्र साझाकरण स्थिति उपलब्ध नहीं है। बदलने से पहले रीफ़्रेश करें।",
    "ChatGPT session sharing enabled for local router clients.": "स्थानीय राउटर क्लाइंट के लिए ChatGPT सत्र साझाकरण चालू किया गया।",
    "ChatGPT session sharing disabled. Installed client catalogs were refreshed.": "ChatGPT सत्र साझाकरण बंद किया गया। इंस्टॉल किए गए क्लाइंट कैटलॉग रीफ़्रेश किए गए।",
    "Native GPT + external models · task history preserved": "नेटिव GPT + बाहरी मॉडल · कार्य इतिहास सुरक्षित",
    "Keep ChatGPT login and the current task history": "ChatGPT लॉगिन और वर्तमान कार्य इतिहास रखें",
    "Use without OpenAI login": "OpenAI लॉगिन के बिना उपयोग करें",
    "External providers · Codex restarts automatically": "बाहरी प्रदाता · Codex स्वचालित रूप से पुनः आरंभ होता है",
    "Use connected models and restart Codex": "कनेक्टेड मॉडल उपयोग करें और Codex पुनः आरंभ करें",
    "Token maxxing": "Token maxxing",
    "Forced off by CODEX_ROUTER_TOOL_RESULT_AGING=0": "CODEX_ROUTER_TOOL_RESULT_AGING=0 द्वारा जबरन बंद",
    "External models · applies on the next request": "बाहरी मॉडल · अगले अनुरोध पर लागू होता है",
    "Providers": "प्रदाता",
    "Auto-saved": "स्वतः सहेजा गया",
    "Applying…": "लागू हो रहा है…",
    "Subagent models": "सबएजेंट मॉडल",
    "All proven models": "सभी सत्यापित मॉडल",
    "Model picker": "मॉडल पिकर",
    "Local LLMs": "स्थानीय LLM",
    "Vision": "विज़न",
    "Subagent choices do not hide models from Codex's picker — use Model picker below for that.": "सबएजेंट विकल्प Codex के पिकर से मॉडल नहीं छिपाते — उसके लिए नीचे मॉडल पिकर का उपयोग करें।",
    "Hidden models stay connected but are not offered by Codex.": "छिपाए गए मॉडल कनेक्टेड रहते हैं, लेकिन Codex द्वारा पेश नहीं किए जाते।",
    "Run models locally through Ollama. Enable an installed model to make it available to Codex.": "Ollama के माध्यम से मॉडल स्थानीय रूप से चलाएँ। इंस्टॉल किए गए मॉडल को Codex के लिए उपलब्ध कराने हेतु उसे सक्षम करें।",
    "Run local models through Ollama or the curated MLX runtime. Installed models are wired into the same Codex proxy.": "Ollama या चुने गए MLX रनटाइम से स्थानीय मॉडल चलाएँ। इंस्टॉल किए गए मॉडल उसी Codex प्रॉक्सी से जोड़े जाते हैं।",
    "Nothing installed yet. Start with a quick pick or browse the Ollama catalog below.": "अभी कुछ भी इंस्टॉल नहीं है। किसी त्वरित विकल्प से शुरू करें या नीचे Ollama कैटलॉग ब्राउज़ करें।",
    "Install a model": "मॉडल इंस्टॉल करें",
    "Install": "इंस्टॉल करें",
    "Clear": "साफ़ करें",
    "Download": "डाउनलोड करें",
    "Cancel": "रद्द करें",
    "Confirm": "पुष्टि करें",
    "Confirm removal?": "हटाने की पुष्टि करें?",
    "Remove model": "मॉडल हटाएँ",
    "Measure speed": "गति मापें",
    "Test image reading": "छवि पठन का परीक्षण करें",
    "Use for image reading": "छवि पठन के लिए उपयोग करें",
    "Reading images": "छवियाँ पढ़ी जा रही हैं",
    "loaded": "लोड हो गया",
    "Installing local model": "स्थानीय मॉडल इंस्टॉल हो रहा है",
    "Local model ready": "स्थानीय मॉडल तैयार है",
    "Local model install failed": "स्थानीय मॉडल इंस्टॉल विफल",
    "Text-only models can't see images. When on, a vision model reads the paste and hands over the text.": "केवल-टेक्स्ट मॉडल छवियाँ नहीं देख सकते। चालू होने पर, एक विज़न मॉडल पेस्ट पढ़कर टेक्स्ट सौंप देता है।",
    "Read images for text-only models": "केवल-टेक्स्ट मॉडलों के लिए छवियाँ पढ़ें",
    "Engine": "इंजन",
    "Paid (cloud)": "सशुल्क (क्लाउड)",
    "Your ChatGPT plan": "आपकी ChatGPT योजना",
    "Cannot run subagents": "सबएजेंट नहीं चला सकता",
    "Effort as subagent": "सबएजेंट के रूप में प्रयास",
    "Model default": "मॉडल डिफ़ॉल्ट",
    "Update": "अपडेट करें",
    "Fix": "ठीक करें",
    "Working…": "काम चल रहा है…",
    "Update or fix failed": "अपडेट या सुधार विफल",
    "Router unavailable": "राउटर अनुपलब्ध",
    "Run setup, then refresh this panel.": "सेटअप चलाएँ, फिर इस पैनल को रीफ़्रेश करें।",
    "Refresh": "रीफ़्रेश करें",
    "Refreshing…": "रीफ़्रेश हो रहा है…",
    "%d accounts": "%d खाते",
    "1 account": "1 खाता",
    "Restart": "पुनः आरंभ करें",
    "Restarting…": "पुनः आरंभ हो रहा है…",
    "Restart failed: %@": "पुनः आरंभ विफल: %@",
    "Restarted without updating: %@": "बिना अपडेट किए पुनः आरंभ हुआ: %@",
    "Awaiting data": "डेटा की प्रतीक्षा में",
    "Quit": "बाहर निकलें",
    "API key": "API कुंजी",
    "Replacement %@": "प्रतिस्थापन %@",
    "Paste %@": "%@ पेस्ट करें",
    "Click the check again to delete this credential": "इस क्रेडेंशियल को हटाने के लिए चेक पर फिर से क्लिक करें",
    "Checking setup…": "सेटअप की जाँच हो रही है…",
    "Session expired · reconnect for account usage": "सत्र समाप्त · खाता उपयोग के लिए पुनः कनेक्ट करें",
    "Official CLI required": "आधिकारिक CLI आवश्यक",
    "Sign in with the official CLI": "आधिकारिक CLI से साइन इन करें",
    "Operator-owned Google OAuth client required": "ऑपरेटर के स्वामित्व वाला Google OAuth क्लाइंट आवश्यक",
    "Live test required · sends a small prompt and uses quota": "लाइव परीक्षण आवश्यक · एक छोटा प्रॉम्प्ट भेजता है और कोटा उपयोग करता है",
    "Disconnect the incompatible router record before signing in": "साइन इन करने से पहले असंगत राउटर रिकॉर्ड को डिस्कनेक्ट करें",
    "Setup required": "सेटअप आवश्यक",
    "Reconnect": "पुनः कनेक्ट करें",
    "Reconnect OAuth": "OAuth पुनः कनेक्ट करें",
    "Open browser sign-in": "ब्राउज़र साइन-इन खोलें",
    "Finish sign-in in browser": "ब्राउज़र में साइन-इन पूरा करें",
    "OAuth sessions refresh automatically. Reconnect opens browser sign-in when approval is required.": "OAuth सत्र अपने आप रीफ़्रेश होते हैं। दोबारा अनुमति चाहिए तो पुनः कनेक्ट ब्राउज़र साइन-इन खोलता है।",
    "Install & Sign In": "इंस्टॉल करें और साइन इन करें",
    "Sign In": "साइन इन करें",
    "Install the official CLI and sign in": "आधिकारिक CLI इंस्टॉल करें और साइन इन करें",
    "Sign in again with the official CLI": "आधिकारिक CLI से फिर से साइन इन करें",
    "Cancel credential replacement": "क्रेडेंशियल प्रतिस्थापन रद्द करें",
    "Click again to delete the stored credential": "सहेजे गए क्रेडेंशियल को हटाने के लिए फिर से क्लिक करें",
    "Remove stored OAuth client and session": "सहेजा गया OAuth क्लाइंट और सत्र हटाएँ",
    "Test & Enable": "परीक्षण करें और सक्षम करें",
    "Remove stored %@": "सहेजा गया %@ हटाएँ",
    "Available in Codex": "Codex में उपलब्ध",
    "Hidden from Codex": "Codex से छिपा हुआ",
    "Signed in": "साइन इन है",
    "Add Key": "कुंजी जोड़ें",
    "Save": "सहेजें",
    "Open usage dashboard": "उपयोग डैशबोर्ड खोलें",
    "Daily token usage": "दैनिक टोकन उपयोग",
    "Full": "पूर्ण",
    "Full token numbers": "पूर्ण टोकन संख्याएँ",
    "Millions of tokens": "मिलियन टोकन",
    "Token unit": "टोकन इकाई",
    "Router traffic": "राउटर ट्रैफ़िक",
    "Loading provider usage…": "प्रदाता उपयोग लोड हो रहा है…",
    "Loading native Codex usage…": "नेटिव Codex उपयोग लोड हो रहा है…",
    "Set up this provider below to fetch its account usage.": "खाता उपयोग प्राप्त करने के लिए नीचे इस प्रदाता को सेट करें।",
    "Usage limit": "उपयोग सीमा",
    "No reset reported": "कोई रीसेट समय नहीं बताया गया",
    "Reconnect below": "नीचे पुनः कनेक्ट करें",
    "OAuth expired · reconnect below": "OAuth समाप्त · नीचे पुनः कनेक्ट करें",
    "No router traffic yet": "अभी तक कोई राउटर ट्रैफ़िक नहीं",
    "Configured · currently hidden": "कॉन्फ़िगर किया गया · वर्तमान में छिपा हुआ",
    "Sign in again to restore quota": "कोटा बहाल करने के लिए फिर से साइन इन करें",
    "Local router traffic": "स्थानीय राउटर ट्रैफ़िक",
    "What do these tags mean?": "इन टैग का क्या अर्थ है?",
    "Hide tag guide": "टैग गाइड छिपाएँ",
    "Show fewer tags": "कम टैग दिखाएँ",
    "View all %@ tags": "सभी %@ टैग देखें",
    "Hide machine & runtime": "मशीन और रनटाइम छिपाएँ",
    "Machine & runtime": "मशीन और रनटाइम",
    "Show fewer quick picks": "कम त्वरित विकल्प दिखाएँ",
    "View more quick picks": "और त्वरित विकल्प देखें",
    "Show all": "सभी दिखाएँ",
    "Hide all": "सभी छिपाएँ",
    "Update and verify Codex Router": "Codex राउटर अपडेट और सत्यापित करें",
    "Running Codex Router maintenance": "Codex राउटर रखरखाव चल रहा है",
    "Daily token usage chart. Hover a day for its displayed token count.": "दैनिक टोकन उपयोग चार्ट। किसी दिन की दिखाई गई टोकन संख्या देखने के लिए उस पर होवर करें।",
    "Show %@ usage": "%@ उपयोग दिखाएँ",
    "WEEKLY LEFT": "साप्ताहिक शेष",
    "TODAY TOKENS": "आज के टोकन",
    "DAILY USAGE": "दैनिक उपयोग",
    "LAST 7 DAYS": "पिछले 7 दिन",
    "Collapse": "समेटें",
    "TODAY'S TOKENS": "आज के टोकन",
    "DAILY TOKEN TREND": "दैनिक टोकन रुझान",
    "ACTIVE NOW": "अभी सक्रिय",
    "ACTIVE PROVIDER": "सक्रिय प्रदाता",
    "USED": "उपयोग हुआ",
    "Account and traffic are provider-scoped": "खाता और ट्रैफ़िक प्रदाता के दायरे में हैं",
    "Live": "लाइव",
    "Last used": "अंतिम उपयोग",
    "Running chats": "चल रही चैट",
    "Router overview": "राउटर अवलोकन",
    "Ready": "तैयार",
    "CHATGPT • NATIVE": "CHATGPT · नेटिव",
    "XAI • OAUTH SESSION": "XAI · OAUTH सत्र",
    "XAI • METERED API": "XAI · मीटर्ड API",
    "METERED API": "मीटर्ड API",
    "OAUTH ROUTE": "OAUTH रूट",
    "ChatGPT account usage": "ChatGPT खाता उपयोग",
    "Measured by this router": "इस राउटर द्वारा मापा गया",
    "Not reported by provider": "प्रदाता द्वारा नहीं बताया गया",
    "Thinking · %@": "सोच रहा है · %@",
    "ROUTER": "राउटर",
    "QUOTAS": "कोटा",
    "Connect a provider to see its quota here.": "यहाँ कोटा देखने के लिए कोई प्रदाता कनेक्ट करें।",
    "DAILY TOKENS": "दैनिक टोकन",
    "resets soon": "जल्द रीसेट होगा",
    "Download anyway?": "फिर भी डाउनलोड करें?",
    "local model": "स्थानीय मॉडल",
    "none installed": "कुछ भी इंस्टॉल नहीं",
    "installed": "इंस्टॉल है",
    "ON THIS MAC": "इस Mac पर",
    "MODEL": "मॉडल",
    "SIZE": "आकार",
    "QUICK PICKS": "त्वरित विकल्प",
    "shortlist for this Mac": "इस Mac के लिए चुनिंदा सूची",
    "CODING": "कोडिंग",
    "IMAGE READING": "छवि पठन",
    "DISCOVER OLLAMA": "Ollama खोजें",
    "cloud-only": "केवल-क्लाउड",
    "Size tags choose the model scale. Q4/Q8/BF16 are weight precision; MLX/NVFP4 are hardware-oriented builds; cloud tags run remotely. Codex compatibility is checked only after a pull.": "आकार टैग मॉडल का पैमाना चुनते हैं। Q4/Q8/BF16 वेट परिशुद्धता हैं; MLX/NVFP4 हार्डवेयर-उन्मुख बिल्ड हैं; क्लाउड टैग दूरस्थ रूप से चलते हैं। Codex संगतता केवल पुल के बाद जाँची जाती है।",
    "Search family or tag": "परिवार या टैग खोजें",
    "INSTALL A MODEL": "मॉडल इंस्टॉल करें",
    "Ollama tag or URL": "Ollama टैग या URL",
    "Use a tag or model-page URL. Downloads stay headless.": "टैग या मॉडल-पेज URL का उपयोग करें। डाउनलोड पृष्ठभूमि में चलते हैं।",
    "gemma4:12b or ollama.com/library/gemma4:12b": "gemma4:12b या ollama.com/library/gemma4:12b",
    "BEST FIT FOR THIS MAC": "इस Mac के लिए सर्वोत्तम",
    "CLOUD ONLY · NO LOCAL DOWNLOAD": "केवल क्लाउड · कोई स्थानीय डाउनलोड नहीं",
    "NO LOCAL VARIANT FITS THIS MAC": "कोई स्थानीय वैरिएंट इस Mac पर फ़िट नहीं",
    "managed": "प्रबंधित",
    "not started": "शुरू नहीं हुआ",
    "Models:": "मॉडल:",
    "Update Ollama": "Ollama अपडेट करें",
    "cloud": "क्लाउड",
    "won't fit": "फ़िट नहीं होगा",
    "cloud only": "केवल क्लाउड",
    "Anyway": "फिर भी",
    "Default": "डिफ़ॉल्ट",
    "Cloud": "क्लाउड",
    "Apple Silicon build": "Apple Silicon बिल्ड",
    "NVFP4 build": "NVFP4 बिल्ड",
    "4-bit build": "4-बिट बिल्ड",
    "8-bit build": "8-बिट बिल्ड",
    "BF16 build": "BF16 बिल्ड",
    "Coding build": "कोडिंग बिल्ड",
    "Specialized build": "विशेषीकृत बिल्ड",
    "BEST FIT": "सर्वोत्तम फ़िट",
    "CLOUD": "क्लाउड",
    "DEFAULT": "डिफ़ॉल्ट",
    "TIGHT": "मेमोरी तंग",
    "WON'T FIT": "फ़िट नहीं",
    "memory tight": "मेमोरी तंग",
    "verified": "सत्यापित",
    "untested": "अपरीक्षित",
    "accurate": "सटीक",
    "inaccurate": "असटीक",
    "tight": "तंग",
    "too-large": "बहुत बड़ा",
    "good": "उपयुक्त",
    "tags": "टैग",
    "fit": "फ़िट",
    "none fit": "कोई फ़िट नहीं",
    "Local model": "स्थानीय मॉडल",
    "Installing": "इंस्टॉल हो रहा है",
    "testing…": "परीक्षण हो रहा है…",
    "Actions for %@": "%@ के लिए कार्रवाइयाँ",
    "speed unmeasured": "गति नहीं मापी गई",
    "vision only — no tools": "केवल विज़न — कोई टूल नहीं",
    "Downloading": "डाउनलोड हो रहा है",
    "Last download failed": "पिछला डाउनलोड विफल",
    "ChatGPT subscription": "ChatGPT सदस्यता",
    "measured on this Mac": "इस Mac पर मापा गया",
    "tokens": "टोकन",
    "requests": "अनुरोध",
    "All good": "सब ठीक है",
    "Router ready": "राउटर तैयार",
    "Current limit": "वर्तमान सीमा",
    "Daily limit": "दैनिक सीमा",
    "Weekly limit": "साप्ताहिक सीमा",
    "Monthly limit": "मासिक सीमा",
    "5-hour limit": "5-घंटे की सीमा",
    "Hidden from picker — show it below to use it here": "पिकर से छिपा है — यहाँ उपयोग करने के लिए इसे नीचे दिखाएँ",
    "Apply the checked-out router revision, then run the Codex doctor": "चेक-आउट किया गया राउटर संस्करण लागू करें, फिर Codex doctor चलाएँ",
    "Run the Codex doctor and repair managed router files": "Codex doctor चलाएँ और प्रबंधित राउटर फ़ाइलें ठीक करें",
    "Sign in or paste an API key": "साइन इन करें या API कुंजी पेस्ट करें",
    "required": "आवश्यक",
    "Checking…": "जाँच हो रही है…",
    "Reading via": "पठन इंजन",
    "Off — text-only models refuse pasted images": "बंद — केवल-टेक्स्ट मॉडल पेस्ट की गई छवियाँ अस्वीकार करते हैं",
    "Daily token usage line chart": "दैनिक टोकन उपयोग रेखा चार्ट",
    "agent": "एजेंट",
    "agents": "एजेंट",
    "Active": "सक्रिय",
    "Low": "कम",
    "Medium": "मध्यम",
    "High": "उच्च",
    "Model provider": "मॉडल प्रदाता",
    "Resets": "रीसेट समय",
    "Menu bar mode": "मेनू बार मोड",
    "Standard": "मानक",
    "Icon only": "केवल आइकन",
    "Compact icon only, no model name text": "केवल कॉम्पैक्ट आइकन, मॉडल नाम टेक्स्ट नहीं",
    "Show icon, model name, and usage": "आइकन, मॉडल नाम और उपयोग दिखाएँ",
    "Show model name": "मॉडल नाम दिखाएँ",
    "Current model or provider is visible in menu bar": "मेनू बार में वर्तमान मॉडल या प्रदाता दिखाई देता है",
    "Hide model name text in menu bar": "मेनू बार में मॉडल नाम टेक्स्ट छिपाएँ",
    "Menu bar icon": "मेनू बार आइकन",
    "Router mark": "राउटर चिह्न",
    "Provider icon": "प्रदाता आइकन",
    "Activity dot": "गतिविधि बिंदु",
    "Preset icon": "प्रीसेट आइकन",
    "Custom image": "कस्टम छवि",
    "Choose the icon displayed in the menu bar": "मेनू बार में दिखाई देने वाला आइकन चुनें",
    "Choose Image…": "छवि चुनें…",
    "No custom image selected": "कोई कस्टम छवि चयनित नहीं",
    "Custom image missing": "कस्टम छवि मौजूद नहीं है",
    "Codex Router · %@ (%@) · %@": "Codex Router · %@ (%@) · %@",
    "Codex Router · %@ (%@)": "Codex Router · %@ (%@)",
    "Select": "चुनें",
    "Service health": "सेवा स्वास्थ्य",
    "Checking": "जाँचा जा रहा है",
    "All clear": "सब ठीक है",
    "Serving locally": "स्थानीय रूप से सेवा दे रहा है",
    "Degraded": "क्षीण",
    "Offline": "ऑफ़लाइन",
    "Health endpoint unavailable": "स्वास्थ्य एंडपॉइंट उपलब्ध नहीं है",
    "Unknown": "अज्ञात",
    "Waiting for health report": "स्वास्थ्य रिपोर्ट की प्रतीक्षा है",
    "Standby": "स्टैंडबाय",
    "Not enabled": "सक्षम नहीं है",
    "Unreachable": "पहुँच से बाहर",
    "Reachable": "पहुँच योग्य",
    "External forwarders": "बाहरी फ़ॉरवर्डर",
    "Subagent": "उप-एजेंट",
    "thinking": "विचार",

    // Provider catalogs: the on-demand panel that asks a configured
    // provider for its current model list and curates from it.
    "Provider catalogs": "प्रदाता कैटलॉग",
    "Load the latest provider models": "प्रदाता के नवीनतम मॉडल लोड करें",
    "Connect a supported provider to load its latest models.": "इसके नवीनतम मॉडल लोड करने के लिए एक समर्थित प्रदाता कनेक्ट करें।",
    "Load models asks that provider for its current list. Choosing models adds them to the router and republishes every installed client.": "\"मॉडल लोड करें\" उस प्रदाता से उसकी वर्तमान सूची माँगता है। मॉडल चुनने पर वे राउटर में जुड़ते हैं और हर इंस्टॉल किए गए क्लाइंट को फिर से प्रकाशित किया जाता है।",
    "Reload provider models": "प्रदाता मॉडल फिर से लोड करें",
    "Reloading provider models…": "प्रदाता मॉडल फिर से लोड हो रहे हैं…",
    "Fetch the current catalog from every connected provider that supports live model discovery.": "लाइव मॉडल खोज का समर्थन करने वाले हर कनेक्टेड प्रदाता से वर्तमान कैटलॉग प्राप्त करें।",
    "Refresh models": "मॉडल रीफ़्रेश करें",
    "Reload installed and available local models from the router.": "राउटर से इंस्टॉल किए गए और उपलब्ध लोकल मॉडल फिर से लोड करें।",
    "Loading models": "मॉडल लोड हो रहे हैं",
    "Search available models": "उपलब्ध मॉडल खोजें",
    "No provider models match this search.": "इस खोज से कोई प्रदाता मॉडल मेल नहीं खाता।",
    "Search providers": "प्रदाता खोजें",
    "No providers match this search.": "इस खोज से कोई प्रदाता मेल नहीं खाता।",
    "Search subagent models": "सबएजेंट मॉडल खोजें",
    "No subagent models match this search.": "इस खोज से कोई सबएजेंट मॉडल मेल नहीं खाता।",
    "Clear search": "खोज साफ़ करें",
    "Added": "जोड़ा गया",
    "Showing the first 80 matches. Search to narrow the list.": "पहले 80 मिलान दिखाए जा रहे हैं। सूची सीमित करने के लिए खोजें।",
    "%d selected": "%d चयनित",
    "Add selected": "चयनित जोड़ें",
    "Load the current list from this provider.": "इस प्रदाता से वर्तमान सूची लोड करें।",
    "saved list": "सहेजी गई सूची",
    "live list": "लाइव सूची",
    "%d models · %d added · %@": "%d मॉडल · %d जोड़े गए · %@",
  ]
}
