/// Arabic translations for strings rendered by the native tray and
/// Dynamic Island. English source text is the key; see Localization.swift.
enum RouterArabicText {
  static let values: [String: String] = [
    "Uninstalling": "جارٍ الإزالة",
    "Off by default · compacts old results; RTK shapes routed compaction": "معطّل افتراضيًا · يضغط النتائج القديمة؛ ويشكّل RTK الضغط الموجّه",
    "Fix Codex Router installation": "إصلاح تثبيت موجّه Codex",
    "Language": "اللغة",
    "System": "حسب النظام",
    "Tray language. Reopen the panel to apply everywhere.": "لغة شريط القوائم. أعد فتح اللوحة لتطبيقها في كل مكان.",
    "Usage and activity over the notch on every display": "الاستخدام والنشاط فوق النوتش على كل شاشة",
    "Off by default. The menu-bar panel stays available either way.": "معطّل افتراضيًا. تبقى لوحة شريط القوائم متاحة في كل الأحوال.",
    "Idle": "خامل",
    "LOCAL FALLBACK": "احتياطي محلي",
    "local fallback": "احتياطي محلي",
    "%d local fallback dates": "%d من تواريخ الاحتياطي المحلي",
    "1 local fallback date": "تاريخ احتياطي محلي واحد",
    "OpenAI account usage; missing dates use local router fallback": "استخدام حساب OpenAI؛ تستخدم التواريخ المفقودة احتياطي الموجّه المحلي",
    "OpenAI supplied no account bucket for these dates; local router traffic fills the gap. These are not global account totals.": "لم توفّر OpenAI حاويات حساب لهذه التواريخ؛ تملأ حركة الموجّه المحلي الفجوة. هذه ليست إجماليات الحساب العالمي.",
    "Thinking": "يفكّر",
    "Starting": "قيد البدء",
    "Error": "خطأ",
    "Codex subscription": "اشتراك Codex",
    "%@ left": "متبقٍ %@",
    "%d chats": "%d محادثة",
    "Active session": "جلسة نشطة",
    "No traffic": "لا حركة",
    "Ready to enable": "جاهز للتفعيل",
    "Needs setup": "بحاجة إلى إعداد",
    "OAuth · enabled": "OAuth · مفعّل",
    "API · enabled": "API · مفعّل",
    "Always": "دائمًا",
    "With Codex": "مع Codex",
    "Off": "إيقاف",
    "Notch": "النوتش",
    "Desktop": "سطح المكتب",
    "Usage": "الاستخدام",
    "Usage and live activity": "الاستخدام والنشاط المباشر",
    "Status": "الحالة",
    "Settings": "الإعدادات",
    "Control Center": "مركز التحكم",
    "Codex Router": "Codex Router",
    "Updated": "محدَّث",
    "None": "لا شيء",
    "none": "لا شيء",
    "Local": "محلي",
    "Auto": "تلقائي",
    "Codex account": "حساب Codex",
    "ChatGPT %@": "ChatGPT %@",
    "ChatGPT limit": "حد ChatGPT",
    "Current usage": "الاستخدام الحالي",
    "All usage": "كل الاستخدام",
    "7-day snapshot": "لمحة عن آخر 7 أيام",
    "Tokens by model": "الرموز حسب النموذج",
    "Router": "الموجّه",
    "Model speed": "سرعة النموذج",
    "Live requests": "الطلبات المباشرة",
    "Quota resets": "إعادة تعيين الحصة",
    "No traffic right now": "لا توجد حركة حاليًا",
    "Ready for the next request": "جاهز للطلب التالي",
    "No model observed": "لم تتم ملاحظة أي نموذج بعد",
    "No usage recorded yet": "لم يُسجَّل أي استخدام بعد",
    "Waiting": "قيد الانتظار",
    "No samples": "لا توجد عينات",
    "Appears after a metered reply": "يظهر بعد رد محسوب",
    "Observed output throughput": "سرعة الإخراج الملحوظة",
    "Nothing in flight": "لا توجد طلبات جارية",
    "no tools — can't chat": "بدون أدوات — لا يمكن الدردشة",
    "works in Codex": "يعمل في Codex",
    "unreliable in Codex": "غير موثوق في Codex",
    "not offered yet": "غير متوفر بعد",
    "fails in Codex": "يفشل في Codex",
    "chat — untested": "الدردشة — غير مختبرة",
    "Provider added. Restart Codex to refresh its model picker.": "تمت إضافة مزوّد الخدمة. أعد تشغيل Codex لتحديث منتقي النماذج.",
    "Provider hidden. Restart Codex to refresh its model picker.": "تم إخفاء مزوّد الخدمة. أعد تشغيل Codex لتحديث منتقي النماذج.",
    "Show tray": "إظهار أيقونة شريط القوائم",
    "Appears with Codex or ChatGPT, hides when they quit": "تظهر مع Codex أو ChatGPT، وتختفي عند إغلاقهما",
    "Kept on: a terminal session has no window to follow": "تبقى مفعّلة: جلسة الطرفية ليس لها نافذة لتتبعها",
    "DeepSeek Harness": "DeepSeek Harness",
    "Install DeepSeek Harness and publish this router's models into it": "تثبيت DeepSeek Harness ونشر نماذج هذا الموجّه فيه",
    "Not installed · installs the CLI, then publishes this router's models": "غير مثبّت · يثبّت CLI ثم ينشر نماذج هذا الموجّه",
    "Needs Node %@ or newer; this router runs Node %@": "يتطلب Node %@ أو أحدث؛ هذا الموجّه يعمل بـ Node %@",
    "%@ · routed models published · `dsh web` to start": "%@ · نُشرت النماذج الموجَّهة · شغّل `dsh web` للبدء",
    "%@ · installed but not routed here yet": "%@ · مثبّت لكنه غير موصول بهذا الموجّه بعد",
    "%d models published. Run `%@` to start.": "تم نشر %d نموذجًا. شغّل `%@` للبدء.",
    "Installing DeepSeek Harness…": "جارٍ تثبيت DeepSeek Harness…",
    "Publishing routed models…": "جارٍ نشر النماذج الموجَّهة…",
    "Setting up DeepSeek Harness": "جارٍ إعداد DeepSeek Harness",
    "Connect": "اتصال",
    "Open site": "فتح الموقع",
    "Turn off": "إيقاف التشغيل",
    "Disconnect": "قطع الاتصال",
    "Stopping…": "جارٍ الإيقاف…",
    "Stopped. Memory and CPU released.": "تم الإيقاف. حُرِّرت الذاكرة والمعالج.",
    "This harness was started outside the router — stop it where you started it.": "بدأ هذا الـ Harness خارج الموجّه — أوقفه من حيث بدأته.",
    "Stop the harness process and free its memory and CPU": "إيقاف عملية الـ Harness وتحرير ذاكرتها ومعالجها",
    "Disconnecting…": "جارٍ قطع الاتصال…",
    "Turned off. The harness and its own settings were kept.": "تم الإيقاف. تم الاحتفاظ بالـ Harness وإعداداته الخاصة.",
    "Remove this router's models from the harness, keeping the harness itself": "إزالة نماذج هذا الموجّه من الـ Harness مع الاحتفاظ بالـ Harness نفسه",
    "Start": "بدء",
    "Open the DeepSeek Harness browser UI": "فتح واجهة متصفح DeepSeek Harness",
    "Start the DeepSeek Harness browser UI": "بدء واجهة متصفح DeepSeek Harness",
    "Starting DeepSeek Harness…": "جارٍ بدء DeepSeek Harness…",
    "%@ · running at %@": "%@ · يعمل على %@",
    "%@ · routed models published · not running": "%@ · نُشرت النماذج الموجَّهة · غير قيد التشغيل",
    "%d models published. Press play to open the harness.": "تم نشر %d نموذجًا. اضغط زر التشغيل لفتح الـ Harness.",
    "%d models published, but the harness UI did not start: %@": "تم نشر %d نموذجًا، لكن واجهة الـ Harness لم تبدأ: %@",
    "Menu bar icon stays visible": "تبقى أيقونة شريط القوائم ظاهرة",
    "Dynamic Island": "الجزيرة الديناميكية",
    "Quotas and live activity pinned to the desktop": "الحصص والنشاط المباشر مثبّتة على سطح المكتب",
    "Show provider usage and activity status": "إظهار استخدام مزوّد الخدمة وحالة النشاط",
    "Use Router with ChatGPT": "استخدام الموجّه مع ChatGPT",
    "Share ChatGPT subscription": "مشاركة اشتراك ChatGPT",
    "Sharing status unavailable": "حالة المشاركة غير متاحة",
    "Sharing enabled": "المشاركة مفعّلة",
    "Sharing disabled": "المشاركة معطّلة",
    "login usable · about %@h left": "تسجيل الدخول صالح · متبقٍ نحو %@ ساعة",
    "login usable": "تسجيل الدخول صالح",
    "login expired": "انتهت صلاحية تسجيل الدخول",
    "login unavailable · sign-in data detected": "تسجيل الدخول غير متاح · عُثر على بيانات تسجيل دخول",
    "login unavailable · run codex login": "تسجيل الدخول غير متاح · شغّل codex login",
    "Enable ChatGPT session sharing?": "هل تريد تفعيل مشاركة جلسة ChatGPT؟",
    "Enabling lets other local Codex Router clients spend this user's ChatGPT subscription. Only continue for clients you trust on this Mac.": "يتيح التفعيل لعملاء Codex Router المحليين الآخرين استهلاك اشتراك ChatGPT لهذا المستخدم. تابع فقط للعملاء الذين تثق بهم على هذا الـ Mac.",
    "Enable sharing": "تفعيل المشاركة",
    "A usable ChatGPT login is required before sharing can be enabled. Run codex login first.": "يلزم تسجيل دخول ChatGPT صالح قبل تفعيل المشاركة. شغّل codex login أولًا.",
    "ChatGPT session-sharing status is unavailable. Refresh before changing it.": "حالة مشاركة جلسة ChatGPT غير متاحة. حدّث قبل تغييرها.",
    "ChatGPT session sharing enabled for local router clients.": "تم تفعيل مشاركة جلسة ChatGPT لعملاء الموجّه المحليين.",
    "ChatGPT session sharing disabled. Installed client catalogs were refreshed.": "تم تعطيل مشاركة جلسة ChatGPT وتحديث فهارس العملاء المثبتين.",
    "Native GPT + external models · task history preserved": "GPT الأصلي + نماذج خارجية · يُحتفظ بسجل المهام",
    "Keep ChatGPT login and the current task history": "الاحتفاظ بتسجيل الدخول إلى ChatGPT وسجل المهام الحالي",
    "Use without OpenAI login": "الاستخدام بدون تسجيل الدخول إلى OpenAI",
    "External providers · Codex restarts automatically": "مزوّدون خارجيون · يُعاد تشغيل Codex تلقائيًا",
    "Use connected models and restart Codex": "استخدام النماذج المتصلة وإعادة تشغيل Codex",
    "Token maxxing": "Token maxxing",
    "Forced off by CODEX_ROUTER_TOOL_RESULT_AGING=0": "معطّل قسرًا بواسطة CODEX_ROUTER_TOOL_RESULT_AGING=0",
    "External models · applies on the next request": "النماذج الخارجية · يُطبَّق عند الطلب التالي",
    "Providers": "مزوّدو الخدمة",
    "Auto-saved": "حُفظ تلقائيًا",
    "Applying…": "جارٍ التطبيق…",
    "Subagent models": "نماذج الوكلاء الفرعيين",
    "All proven models": "جميع النماذج المتحقق منها",
    "Model picker": "منتقي النماذج",
    "Local LLMs": "نماذج LLM المحلية",
    "Vision": "الرؤية",
    "Subagent choices do not hide models from Codex's picker — use Model picker below for that.": "اختيارات الوكلاء الفرعيين لا تخفي النماذج من منتقي Codex — استخدم منتقي النماذج أدناه لذلك.",
    "Hidden models stay connected but are not offered by Codex.": "تبقى النماذج المخفية متصلة لكنها لا تُعرض على Codex.",
    "Run models locally through Ollama. Enable an installed model to make it available to Codex.": "شغّل النماذج محليًا عبر Ollama. فعّل نموذجًا مثبّتًا لإتاحته لـ Codex.",
    "Run local models through Ollama or the curated MLX runtime. Installed models are wired into the same Codex proxy.": "شغّل النماذج محليًا عبر Ollama أو بيئة MLX المنتقاة. تُوصَل النماذج المثبّتة بوكيل Codex نفسه.",
    "Nothing installed yet. Start with a quick pick or browse the Ollama catalog below.": "لا يوجد شيء مثبّت بعد. ابدأ باختيار سريع أو تصفّح كتالوج Ollama أدناه.",
    "Install a model": "تثبيت نموذج",
    "Install": "تثبيت",
    "Clear": "مسح",
    "Download": "تنزيل",
    "Cancel": "إلغاء",
    "Confirm": "تأكيد",
    "Confirm removal?": "تأكيد الإزالة؟",
    "Remove model": "إزالة النموذج",
    "Measure speed": "قياس السرعة",
    "Test image reading": "اختبار قراءة الصور",
    "Use for image reading": "استخدامه لقراءة الصور",
    "Reading images": "قراءة الصور",
    "loaded": "محمَّل",
    "Installing local model": "جارٍ تثبيت النموذج المحلي",
    "Local model ready": "النموذج المحلي جاهز",
    "Local model install failed": "فشل تثبيت النموذج المحلي",
    "Text-only models can't see images. When on, a vision model reads the paste and hands over the text.": "النماذج النصية فقط لا ترى الصور. عند التفعيل، يقرأ نموذج رؤية المحتوى الملصق ويسلّم النص.",
    "Read images for text-only models": "قراءة الصور للنماذج النصية فقط",
    "Engine": "المحرك",
    "Paid (cloud)": "مدفوع (سحابي)",
    "Your ChatGPT plan": "خطة ChatGPT الخاصة بك",
    "Cannot run subagents": "لا يمكن تشغيل الوكلاء الفرعيين",
    "Effort as subagent": "مستوى التفكير كوكيل فرعي",
    "Model default": "افتراضي النموذج",
    "Update": "تحديث",
    "Fix": "إصلاح",
    "Working…": "جارٍ العمل…",
    "Update or fix failed": "فشل التحديث أو الإصلاح",
    "Router unavailable": "الموجّه غير متاح",
    "Run setup, then refresh this panel.": "شغّل الإعداد ثم حدّث هذه اللوحة.",
    "Refresh": "تحديث",
    "Refreshing…": "جارٍ التحديث…",
    "%d accounts": "%d حساب",
    "1 account": "حساب واحد",
    "Restart": "إعادة تشغيل",
    "Restarting…": "جارٍ إعادة التشغيل…",
    "Restart failed: %@": "فشلت إعادة التشغيل: %@",
    "Restarted without updating: %@": "أُعيد التشغيل دون تحديث: %@",
    "Awaiting data": "بانتظار البيانات",
    "Quit": "إنهاء",
    "API key": "مفتاح API",
    "Replacement %@": "استبدال %@",
    "Paste %@": "لصق %@",
    "Click the check again to delete this credential": "انقر علامة الاختيار مرة أخرى لحذف بيانات الاعتماد هذه",
    "Checking setup…": "جارٍ فحص الإعداد…",
    "Session expired · reconnect for account usage": "انتهت الجلسة · أعد الاتصال لعرض استخدام الحساب",
    "Official CLI required": "يتطلب CLI الرسمي",
    "Sign in with the official CLI": "سجّل الدخول باستخدام CLI الرسمي",
    "Operator-owned Google OAuth client required": "مطلوب عميل Google OAuth مملوك للمشغّل",
    "Live test required · sends a small prompt and uses quota": "يلزم اختبار مباشر · يرسل مطالبة قصيرة ويستهلك الحصة",
    "Disconnect the incompatible router record before signing in": "افصل سجل جهاز التوجيه غير المتوافق قبل تسجيل الدخول",
    "Setup required": "الإعداد مطلوب",
    "Reconnect": "إعادة الاتصال",
    "Reconnect OAuth": "إعادة اتصال OAuth",
    "Open browser sign-in": "فتح تسجيل الدخول في المتصفح",
    "Finish sign-in in browser": "أكمل تسجيل الدخول في المتصفح",
    "OAuth sessions refresh automatically. Reconnect opens browser sign-in when approval is required.": "تتجدد جلسات OAuth تلقائيًا. عند الحاجة إلى موافقة جديدة، تفتح إعادة الاتصال تسجيل الدخول في المتصفح.",
    "Install & Sign In": "التثبيت وتسجيل الدخول",
    "Sign In": "تسجيل الدخول",
    "Install the official CLI and sign in": "ثبّت CLI الرسمي وسجّل الدخول",
    "Sign in again with the official CLI": "سجّل الدخول مجددًا باستخدام CLI الرسمي",
    "Cancel credential replacement": "إلغاء استبدال بيانات الاعتماد",
    "Click again to delete the stored credential": "انقر مرة أخرى لحذف بيانات الاعتماد المخزّنة",
    "Remove stored OAuth client and session": "إزالة عميل OAuth والجلسة المخزّنين",
    "Test & Enable": "الاختبار والتفعيل",
    "Remove stored %@": "إزالة %@ المخزّن",
    "Available in Codex": "متاح في Codex",
    "Hidden from Codex": "مخفي من Codex",
    "Signed in": "تم تسجيل الدخول",
    "Add Key": "إضافة مفتاح",
    "Save": "حفظ",
    "Open usage dashboard": "فتح لوحة الاستخدام",
    "Daily token usage": "استخدام الرموز اليومي",
    "Full": "كامل",
    "Full token numbers": "أعداد الرموز الكاملة",
    "Millions of tokens": "ملايين الرموز",
    "Token unit": "وحدة الرموز",
    "Router traffic": "حركة الموجّه",
    "Loading provider usage…": "جارٍ تحميل استخدام مزوّد الخدمة…",
    "Loading native Codex usage…": "جارٍ تحميل استخدام Codex الأصلي…",
    "Set up this provider below to fetch its account usage.": "أعدّ مزوّد الخدمة هذا أدناه لجلب استخدام حسابه.",
    "Usage limit": "حد الاستخدام",
    "No reset reported": "لم يُبلَّغ عن وقت إعادة تعيين",
    "Reconnect below": "أعد الاتصال أدناه",
    "OAuth expired · reconnect below": "انتهت صلاحية OAuth · أعد الاتصال أدناه",
    "No router traffic yet": "لا حركة عبر الموجّه بعد",
    "Configured · currently hidden": "مُعدّ · مخفي حاليًا",
    "Sign in again to restore quota": "سجّل الدخول مجددًا لاستعادة الحصة",
    "Local router traffic": "حركة الموجّه المحلية",
    "What do these tags mean?": "ماذا تعني هذه الوسوم؟",
    "Hide tag guide": "إخفاء دليل الوسوم",
    "Show fewer tags": "إظهار وسوم أقل",
    "View all %@ tags": "عرض جميع الوسوم الـ %@",
    "Hide machine & runtime": "إخفاء الجهاز وبيئة التشغيل",
    "Machine & runtime": "الجهاز وبيئة التشغيل",
    "Show fewer quick picks": "إظهار اختيارات سريعة أقل",
    "View more quick picks": "عرض مزيد من الاختيارات السريعة",
    "Show all": "إظهار الكل",
    "Hide all": "إخفاء الكل",
    "Update and verify Codex Router": "تحديث موجّه Codex والتحقق منه",
    "Running Codex Router maintenance": "جارٍ صيانة موجّه Codex",
    "Daily token usage chart. Hover a day for its displayed token count.": "مخطط استخدام الرموز اليومي. مرّر المؤشر فوق يوم لعرض عدد رموزه المعروض.",
    "Show %@ usage": "إظهار استخدام %@",
    "WEEKLY LEFT": "المتبقي أسبوعيًا",
    "TODAY TOKENS": "رموز اليوم",
    "DAILY USAGE": "الاستخدام اليومي",
    "LAST 7 DAYS": "آخر 7 أيام",
    "Collapse": "طي",
    "TODAY'S TOKENS": "رموز اليوم",
    "DAILY TOKEN TREND": "اتجاه الرموز اليومي",
    "ACTIVE NOW": "نشط الآن",
    "ACTIVE PROVIDER": "المزوّد النشط",
    "USED": "المستخدم",
    "Account and traffic are provider-scoped": "الحساب والحركة مرتبطان بكل مزوّد خدمة",
    "Live": "مباشر",
    "Last used": "آخر استخدام",
    "Running chats": "محادثات قيد التشغيل",
    "Router overview": "نظرة عامة على الموجّه",
    "Ready": "جاهز",
    "CHATGPT • NATIVE": "CHATGPT · أصلي",
    "XAI • OAUTH SESSION": "XAI · جلسة OAUTH",
    "XAI • METERED API": "XAI · API محسوب",
    "METERED API": "API محسوب",
    "OAUTH ROUTE": "مسار OAUTH",
    "ChatGPT account usage": "استخدام حساب ChatGPT",
    "Measured by this router": "مُقاس بواسطة هذا الموجّه",
    "Not reported by provider": "لم يبلّغ عنه مزوّد الخدمة",
    "Thinking · %@": "يفكّر · %@",
    "ROUTER": "الموجّه",
    "QUOTAS": "الحصص",
    "Connect a provider to see its quota here.": "اربط مزوّد خدمة لعرض حصته هنا.",
    "DAILY TOKENS": "الرموز اليومية",
    "resets soon": "يُعاد تعيينه قريبًا",
    "Download anyway?": "التنزيل على أي حال؟",
    "local model": "نموذج محلي",
    "none installed": "لا شيء مثبّت",
    "installed": "مثبّت",
    "ON THIS MAC": "على هذا الجهاز",
    "MODEL": "النموذج",
    "SIZE": "الحجم",
    "QUICK PICKS": "اختيارات سريعة",
    "shortlist for this Mac": "قائمة مختارة لهذا الجهاز",
    "CODING": "البرمجة",
    "IMAGE READING": "قراءة الصور",
    "DISCOVER OLLAMA": "اكتشف Ollama",
    "cloud-only": "سحابي فقط",
    "Size tags choose the model scale. Q4/Q8/BF16 are weight precision; MLX/NVFP4 are hardware-oriented builds; cloud tags run remotely. Codex compatibility is checked only after a pull.": "وسوم الحجم تحدد حجم النموذج. Q4/Q8/BF16 هي دقة الأوزان؛ وMLX/NVFP4 نسخ موجّهة للعتاد؛ والوسوم السحابية تعمل عن بُعد. لا يُفحص توافق Codex إلا بعد سحب النموذج.",
    "Search family or tag": "ابحث عن عائلة أو وسم",
    "INSTALL A MODEL": "تثبيت نموذج",
    "Ollama tag or URL": "وسم Ollama أو رابط URL",
    "Use a tag or model-page URL. Downloads stay headless.": "استخدم وسمًا أو رابط صفحة النموذج. تجري التنزيلات في الخلفية.",
    "gemma4:12b or ollama.com/library/gemma4:12b": "gemma4:12b أو ollama.com/library/gemma4:12b",
    "BEST FIT FOR THIS MAC": "الأنسب لهذا الجهاز",
    "CLOUD ONLY · NO LOCAL DOWNLOAD": "سحابي فقط · بدون تنزيل محلي",
    "NO LOCAL VARIANT FITS THIS MAC": "لا توجد نسخة محلية تناسب هذا الجهاز",
    "managed": "مُدار",
    "not started": "لم يبدأ",
    "Models:": "النماذج:",
    "Update Ollama": "تحديث Ollama",
    "cloud": "سحابي",
    "won't fit": "لا يتسع",
    "cloud only": "سحابي فقط",
    "Anyway": "على أي حال",
    "Default": "افتراضي",
    "Cloud": "سحابي",
    "Apple Silicon build": "نسخة Apple Silicon",
    "NVFP4 build": "نسخة NVFP4",
    "4-bit build": "نسخة 4 بت",
    "8-bit build": "نسخة 8 بت",
    "BF16 build": "نسخة BF16",
    "Coding build": "نسخة برمجة",
    "Specialized build": "نسخة متخصصة",
    "BEST FIT": "الأنسب",
    "CLOUD": "سحابي",
    "DEFAULT": "افتراضي",
    "TIGHT": "ذاكرة ضيقة",
    "WON'T FIT": "لا يتسع",
    "memory tight": "الذاكرة ضيقة",
    "verified": "متحقق منه",
    "untested": "غير مختبر",
    "accurate": "دقيق",
    "inaccurate": "غير دقيق",
    "tight": "ضيق",
    "too-large": "كبير جدًا",
    "good": "مناسب",
    "tags": "وسوم",
    "fit": "متوافق",
    "none fit": "لا شيء متوافق",
    "Local model": "نموذج محلي",
    "Installing": "جارٍ التثبيت",
    "testing…": "جارٍ الاختبار…",
    "Actions for %@": "إجراءات %@",
    "speed unmeasured": "السرعة غير مقيسة",
    "vision only — no tools": "رؤية فقط — بدون أدوات",
    "Downloading": "جارٍ التنزيل",
    "Last download failed": "فشل التنزيل الأخير",
    "ChatGPT subscription": "اشتراك ChatGPT",
    "measured on this Mac": "مُقاس على هذا الجهاز",
    "tokens": "رموز",
    "requests": "طلبات",
    "All good": "كل شيء على ما يرام",
    "Router ready": "الموجّه جاهز",
    "Current limit": "الحد الحالي",
    "Daily limit": "الحد اليومي",
    "Weekly limit": "الحد الأسبوعي",
    "Monthly limit": "الحد الشهري",
    "5-hour limit": "حد 5 ساعات",
    "Hidden from picker — show it below to use it here": "مخفي من المنتقي — أظهره أدناه لاستخدامه هنا",
    "Apply the checked-out router revision, then run the Codex doctor": "تطبيق نسخة الموجّه المسحوبة ثم تشغيل Codex doctor",
    "Run the Codex doctor and repair managed router files": "تشغيل Codex doctor وإصلاح ملفات الموجّه المُدارة",
    "Sign in or paste an API key": "سجّل الدخول أو الصق مفتاح API",
    "required": "مطلوب",
    "Checking…": "جارٍ الفحص…",
    "Reading via": "القراءة عبر",
    "Off — text-only models refuse pasted images": "معطّل — النماذج النصية فقط ترفض الصور الملصقة",
    "Daily token usage line chart": "مخطط خطي لاستخدام الرموز اليومي",
    "agent": "وكيل",
    "agents": "وكلاء",
    "Active": "نشط",
    "Low": "منخفض",
    "Medium": "متوسط",
    "High": "مرتفع",
    "Model provider": "مزوّد النماذج",
    "Resets": "وقت إعادة التعيين",
    "Menu bar mode": "وضع شريط القوائم",
    "Standard": "القياسي",
    "Icon only": "أيقونة فقط",
    "Compact icon only, no model name text": "أيقونة مدمجة فقط، دون نص اسم النموذج",
    "Show icon, model name, and usage": "عرض الأيقونة واسم النموذج والاستخدام",
    "Show model name": "عرض اسم النموذج",
    "Current model or provider is visible in menu bar": "يظهر اسم النموذج أو المزوّد الحالي في شريط القوائم",
    "Hide model name text in menu bar": "إخفاء نص اسم النموذج في شريط القوائم",
    "Menu bar icon": "أيقونة شريط القوائم",
    "Router mark": "علامة الموجّه",
    "Provider icon": "أيقونة المزوّد",
    "Activity dot": "نقطة النشاط",
    "Preset icon": "أيقونة محددة مسبقًا",
    "Custom image": "صورة مخصصة",
    "Choose the icon displayed in the menu bar": "اختر الأيقونة المعروضة في شريط القوائم",
    "Choose Image…": "اختر صورة…",
    "No custom image selected": "لم يتم تحديد صورة مخصصة",
    "Custom image missing": "الصورة المخصصة مفقودة",
    "Codex Router · %@ (%@) · %@": "Codex Router · %@ (%@) · %@",
    "Codex Router · %@ (%@)": "Codex Router · %@ (%@)",
    "Select": "تحديد",
    "Service health": "صحة الخدمة",
    "Checking": "جارٍ التحقق",
    "All clear": "كل شيء سليم",
    "Serving locally": "تعمل محليًا",
    "Degraded": "متدهورة",
    "Offline": "غير متصل",
    "Health endpoint unavailable": "نقطة فحص الصحة غير متاحة",
    "Unknown": "غير معروف",
    "Waiting for health report": "بانتظار تقرير الصحة",
    "Standby": "في وضع الاستعداد",
    "Not enabled": "غير مفعّل",
    "Unreachable": "يتعذر الوصول إليه",
    "Reachable": "يمكن الوصول إليه",
    "External forwarders": "وكلاء التمرير الخارجيون",
    "Subagent": "وكيل فرعي",
    "thinking": "التفكير",

    // Provider catalogs: the on-demand panel that asks a configured
    // provider for its current model list and curates from it.
    "Provider catalogs": "كتالوجات المزوّدين",
    "Load the latest provider models": "حمّل أحدث نماذج المزوّد",
    "Connect a supported provider to load its latest models.": "اتصل بمزوّد مدعوم لتحميل أحدث نماذجه.",
    "Load models asks that provider for its current list. Choosing models adds them to the router and republishes every installed client.": "يطلب «تحميل النماذج» من المزوّد قائمته الحالية. واختيار النماذج يضيفها إلى الموجّه ويعيد نشر كل عميل مثبَّت.",
    "Reload provider models": "إعادة تحميل نماذج المزوّدين",
    "Reloading provider models…": "جارٍ إعادة تحميل نماذج المزوّدين…",
    "Fetch the current catalog from every connected provider that supports live model discovery.": "اجلب الكتالوج الحالي من كل مزوّد متصل يدعم اكتشاف النماذج المباشر.",
    "Refresh models": "تحديث النماذج",
    "Reload installed and available local models from the router.": "أعد تحميل النماذج المحلية المثبَّتة والمتاحة من الموجّه.",
    "Loading models": "جارٍ تحميل النماذج",
    "Search available models": "ابحث في النماذج المتاحة",
    "No provider models match this search.": "لا توجد نماذج مزوّد تطابق هذا البحث.",
    "Search providers": "ابحث عن مزودي الخدمة",
    "No providers match this search.": "لا يوجد مزود خدمة يطابق هذا البحث.",
    "Search subagent models": "ابحث في نماذج الوكلاء الفرعيين",
    "No subagent models match this search.": "لا توجد نماذج وكلاء فرعيين تطابق هذا البحث.",
    "Clear search": "مسح البحث",
    "Added": "مُضاف",
    "Showing the first 80 matches. Search to narrow the list.": "يتم عرض أول 80 نتيجة مطابقة. ابحث لتضييق القائمة.",
    "%d selected": "%d محدَّد",
    "Add selected": "أضف المحدَّد",
    "Load the current list from this provider.": "حمّل القائمة الحالية من هذا المزوّد.",
    "saved list": "قائمة محفوظة",
    "live list": "قائمة مباشرة",
    "%d models · %d added · %@": "%d نموذج · %d مُضاف · %@",
  ]
}
