class CodexRouter < Formula
  desc "Route Codex to non-OpenAI models through a local gateway"
  homepage "https://github.com/duolahypercho/codex-router"
  # NOT YET INSTALLABLE. v0.4.0-beta.2 was tagged on 2026-08-06 and the
  # hash-verified `requirements/` lock landed on 2026-08-08, so the only
  # published release does not contain the file this formula installs the Python
  # gateway from. The url and sha256 below are that release's, and building from
  # them fails on a missing requirements/python.txt.
  #
  # A new main release fixes it and nothing else has to change: the release
  # workflow bumps package.json, tags it, and rewrites both lines in the tap
  # through scripts/update-homebrew-formula.mjs. Verified working against a
  # local archive of main, which is what a new release would contain.
  url "https://github.com/duolahypercho/codex-router/releases/download/v0.4.0-beta.2/codex-router-0.4.0-beta.2.tar.gz"
  sha256 "665511833fe4681c6e2c9e930f4561710ad3d265622ed1fb4fa1df8d24307482"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # Both dependencies are pinned to a major version rather than tracking the
  # rolling `node` and `python3` formulae, because the router fingerprints the
  # interpreter that built each dependency tree: the Node major version for
  # node_modules, and Python's major.minor for the virtualenv (see STEPS in
  # src/install-plan.mjs). Tracking `node` would invalidate that fingerprint on
  # the next `brew upgrade node`, and because a keg cannot rebuild its own
  # dependencies, the router would refuse to start until it was reinstalled.
  # node@24 is also the version the project's own release workflow tests on.
  depends_on "node@24"
  depends_on "python@3.12"

  # Three of LiteLLM's dependencies (jiter, orjson, tiktoken) ship prebuilt macOS
  # wheels whose extension modules are Mach-O dylibs with an `@rpath/...` install
  # name. After the build, Homebrew rewrites the install name of every dylib in
  # the keg to an absolute path, which does not fit in the load-command padding a
  # PyPI wheel was linked with -- Homebrew's own compiler shims pass
  # -headerpad_max_install_names, and the wheel builders do not. The install then
  # fails on the first such file, after the keg is built and working, which reads
  # as a cosmetic warning but exits non-zero.
  #
  # These are Python extension modules, loaded by path through dlopen, so their
  # install name is never consulted by anything. Preserving it is correct rather
  # than merely expedient. The alternative, --no-binary for those three, would put
  # a Rust toolchain and several minutes of compilation in front of every install
  # to change a field nothing reads.
  preserve_rpath

  def node_bin
    formula_opt_bin("node@24")
  end

  def install
    libexec.install Dir["*"]

    cd libexec do
      # One runtime dependency, taken from the committed lockfile. --ignore-scripts
      # because nothing in the tree has a legitimate install hook, and a package
      # that grows one should not get to run it during `brew install`.
      system node_bin/"npm", "ci", "--omit=dev", "--ignore-scripts"

      # requirements/python.txt is the hash-verified transitive closure of the
      # LiteLLM pins in src/install-plan.mjs, so pip verifies every wheel and
      # sdist in the tree against the lock before executing it. Installing from
      # the lock is also why this is not a set of Homebrew `resource` blocks: the
      # closure is 2400 hash lines that would have to be regenerated by hand on
      # every LiteLLM bump, from a file that is already pinned and hashed.
      #
      # The venv is built from python@3.12's *opt* path so its interpreter
      # symlink survives patch upgrades; a minor upgrade is a different matter
      # and needs `brew reinstall codex-router` (see caveats).
      system formula_opt_bin("python@3.12")/"python3.12", "-m", "venv", ".venv"
      system libexec/".venv/bin/python", "-m", "pip", "install", "--disable-pip-version-check",
             "--require-hashes", "-r", "requirements/python.txt"

      # The router skips a dependency step when its stamp matches the current
      # inputs. Recording both here is what makes `codex-router setup` a
      # configuration-only run: without the stamps it would try to rebuild these
      # trees inside a keg it cannot write to.
      system node_bin/"node", "src/install-plan.mjs", "record", "node-deps"
      system node_bin/"node", "src/install-plan.mjs", "record", "python-deps"
    end

    # Everything is addressed through opt_libexec rather than the versioned
    # Cellar path. The router writes these values into the launchd/systemd unit
    # it registers, and a unit naming the Cellar path stops resolving the moment
    # Homebrew cleans up the old keg.
    (bin/"codex-router").write <<~SH
      #!/bin/sh
      # Generated by the codex-router formula. Do not edit; `brew reinstall` rewrites it.
      CODEX_ROUTER_PACKAGE_MANAGER=homebrew
      CODEX_ROUTER_SOURCE_ROOT="#{opt_libexec}"
      CODEX_ROUTER_NODE_BIN="#{node_bin}/node"
      PATH="#{node_bin}:$PATH"
      export CODEX_ROUTER_PACKAGE_MANAGER CODEX_ROUTER_SOURCE_ROOT CODEX_ROUTER_NODE_BIN PATH
      exec "#{opt_libexec}/bin/codex-router" "$@"
    SH
  end

  def caveats
    <<~EOS
      Run the one-time interactive setup before using Codex:
        codex-router setup

      It registers a per-user background service that starts at login, applies the
      managed block in ~/.codex/config.toml, and collects provider credentials.
      After that, run `codex` as usual — routing is transparent.

      Upgrades go through Homebrew:
        brew upgrade codex-router
      `codex-router update` is for Git checkouts and refuses here.

      Two things this install cannot do, both because Homebrew owns the
      application directory:
        - The menu-bar companion app is compiled from source into that
          directory. Install from a Git checkout if you want it.
        - `brew upgrade python@3.12` to a new *minor* version invalidates the
          virtualenv. Run `brew reinstall codex-router` to rebuild it.

      Removing the integration and the background service:
        codex-router uninstall
      Credentials and logs in ~/.codex/codex-router are kept; delete that
      directory to remove them too.
    EOS
  end

  test do
    # The dispatcher resolves its own root through the symlink Homebrew put in
    # bin/, so a wrong root shows up here as a missing package.json rather than
    # at the point someone runs setup.
    assert_match version.to_s, shell_output("#{bin}/codex-router --version")
    assert_match "Usage: codex-router <command>", shell_output("#{bin}/codex-router help")

    # An unknown command must fail rather than resolve to something in bin/.
    assert_match "unknown command", shell_output("#{bin}/codex-router ../install.sh 2>&1", 2)

    # The Python gateway is the half a JS-only smoke test would miss: a venv that
    # imports LiteLLM is the actual thing the router launches at runtime.
    system libexec/".venv/bin/python", "-c", "import litellm"

    # Both dependency stamps have to be present and current, or the first
    # `codex-router setup` refuses instead of configuring.
    ENV["CODEX_ROUTER_SOURCE_ROOT"] = libexec.to_s
    ["node-deps", "python-deps"].each do |step|
      status = shell_output("#{node_bin}/node #{libexec}/src/install-plan.mjs status #{step}").strip
      assert_equal "skip", status
    end
  end
end
