// An opt-in `codex` wrapper that guarantees the router is listening before
// Codex starts.
//
// The tray already starts the router when it sees Codex appear, but it learns
// about a new process by polling, so a cold start races: Codex can send its
// first request before the gateway is accepting connections. The shim closes
// that window by doing the check in the one place that is provably earlier than
// Codex — in front of it.
//
// It is deliberately not part of a normal install. Putting a file named `codex`
// on someone's PATH shadows a command they did not ask us to own, so it happens
// only when they run `model-router codex shim install`.

import {
  accessSync,
  chmodSync,
  constants,
  existsSync,
  mkdirSync,
  readFileSync,
  readlinkSync,
  realpathSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import os from "node:os";
import path from "node:path";

import { PORTS, SOURCE_ROOT, STATE_DIR } from "./paths.mjs";

// Stamped into every generated shim. Detection, refusal-to-clobber, and the
// shim's own "don't exec myself" guard all key off this exact string.
export const SHIM_MARKER = "MODEL_ROUTER_CODEX_SHIM";
export const SHIM_COMMAND = "codex";

// Where the shim goes when no directory already on PATH can host it. Nothing
// puts this on PATH for the user: editing shell rc files behind someone's back
// is worse than telling them one line to add.
export const FALLBACK_SHIM_DIR = path.join(STATE_DIR, "bin");

function pathEntries(environment = process.env) {
  return (environment.PATH || "")
    .split(path.delimiter)
    .map((entry) => (entry === "" ? "." : entry));
}

function isExecutableFile(candidate) {
  try {
    // Follow symlinks: npm installs `codex` as a link into lib/node_modules.
    if (!statSync(candidate).isFile()) return false;
    accessSync(candidate, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

export function isShimFile(candidate) {
  try {
    // Only ever read small text files. A native `codex` binary is tens of
    // megabytes and there is no reason to pull it into memory to answer this.
    if (statSync(candidate).size > 64 * 1024) return false;
    return readFileSync(candidate, "utf8").includes(SHIM_MARKER);
  } catch {
    return false;
  }
}

/**
 * Find the real `codex` on PATH, ignoring any shim we installed.
 *
 * Returns `{ file, directory, index }` where `index` is the position of its
 * directory in PATH, or null when Codex is not installed.
 */
export function resolveRealCodex(environment = process.env) {
  const entries = pathEntries(environment);
  for (let index = 0; index < entries.length; index += 1) {
    const candidate = path.join(entries[index], SHIM_COMMAND);
    if (!isExecutableFile(candidate)) continue;
    if (isShimFile(candidate)) continue;
    return { file: candidate, directory: entries[index], index };
  }
  return null;
}

function isWritableDirectory(directory) {
  try {
    if (!statSync(directory).isDirectory()) return false;
    accessSync(directory, constants.W_OK);
    return true;
  } catch {
    return false;
  }
}

/**
 * Choose where to write the shim.
 *
 * The only requirement that matters is ordering: a shim that sits *behind* the
 * real `codex` on PATH is never executed, which is a silent no-op rather than a
 * visible failure. So candidates are restricted to directories that already
 * precede the real Codex, and the closest one wins — shadowing from as late in
 * PATH as possible keeps the blast radius small.
 *
 * Directories outside the home directory are skipped even when writable.
 * Installing into /usr/local/bin affects every account on the machine, and this
 * command was not asked to make that decision.
 */
export function chooseShimDirectory(real, environment = process.env, home = os.homedir()) {
  const entries = pathEntries(environment);
  const inHome = (directory) => {
    const resolved = path.resolve(directory);
    return resolved === home || resolved.startsWith(`${home}${path.sep}`);
  };

  for (let index = real.index - 1; index >= 0; index -= 1) {
    const directory = entries[index];
    if (!inHome(directory)) continue;
    if (!isWritableDirectory(directory)) continue;
    return { directory, onPath: true };
  }
  return { directory: FALLBACK_SHIM_DIR, onPath: false };
}

function shellQuote(value) {
  return `'${String(value).replaceAll("'", `'\\''`)}'`;
}

export function renderShim({ realCodex, checkout = SOURCE_ROOT, port = PORTS.router }) {
  // bash rather than sh, for /dev/tcp. The probe runs on every single `codex`
  // invocation, so it must not fork: `nc`, `curl`, and a node one-liner all cost
  // more than the check is worth, and nc is not installed everywhere anyway.
  return `#!/bin/bash
# ${SHIM_MARKER}
#
# Generated by \`model-router codex shim install\`. Ensures the Codex Router is
# listening, then hands off to the real Codex. Remove it with
# \`model-router codex shim uninstall\`, or just delete this file.
#
# Every failure path here still execs Codex. A router problem must never be
# allowed to become "codex does not start".

set -u

ROUTER_CHECKOUT=${shellQuote(checkout)}
ROUTER_PORT=${shellQuote(String(port))}
CODEX_BIN=${shellQuote(realCodex)}
# Seconds to wait for a cold router before giving up and starting Codex anyway.
ROUTER_WAIT=\${MODEL_ROUTER_SHIM_WAIT:-45}

# Recorded at install time, but npm reinstalls and version managers move things.
# Fall back to a PATH search that skips this shim rather than failing outright.
if [ ! -x "$CODEX_BIN" ]; then
  found=''
  saved_ifs=$IFS
  IFS=:
  for dir in $PATH; do
    [ -n "$dir" ] || dir='.'
    candidate="$dir/${SHIM_COMMAND}"
    if [ -x "$candidate" ] && ! grep -q ${shellQuote(SHIM_MARKER)} "$candidate" 2>/dev/null; then
      found=$candidate
      break
    fi
  done
  IFS=$saved_ifs
  if [ -z "$found" ]; then
    printf 'codex-router: cannot find the real codex on PATH.\\n' >&2
    exit 127
  fi
  CODEX_BIN=$found
fi

router_listening() {
  (exec 3<>"/dev/tcp/127.0.0.1/$ROUTER_PORT") 2>/dev/null
}

# MODEL_ROUTER_SHIM=0 is the escape hatch for debugging Codex without the router
# in the way.
if [ "\${MODEL_ROUTER_SHIM:-1}" != '0' ] && ! router_listening; then
  if [ -x "$ROUTER_CHECKOUT/bin/control" ]; then
    printf 'codex-router: starting the router...\\n' >&2
    # \`control service start\` blocks until the router reports healthy, and its
    # own budget is 300s. Run it in the background and bound the wait here
    # instead, so a gateway that never comes up delays Codex by seconds rather
    # than by minutes.
    "$ROUTER_CHECKOUT/bin/control" service start >/dev/null 2>&1 &
    waited=0
    while [ "$waited" -lt "$ROUTER_WAIT" ]; do
      if router_listening; then break; fi
      sleep 1
      waited=$((waited + 1))
    done
    if ! router_listening; then
      printf 'codex-router: the router did not come up in %ss; starting Codex anyway.\\n' \\
        "$ROUTER_WAIT" >&2
      printf 'codex-router: run \`%s/bin/model-router codex doctor\` to see why.\\n' \\
        "$ROUTER_CHECKOUT" >&2
    fi
  else
    printf 'codex-router: checkout missing at %s; starting Codex without the router.\\n' \\
      "$ROUTER_CHECKOUT" >&2
  fi
fi

exec "$CODEX_BIN" "$@"
`;
}

export function shimStatus(environment = process.env) {
  const real = resolveRealCodex(environment);
  const entries = pathEntries(environment);
  let installed = null;

  for (let index = 0; index < entries.length; index += 1) {
    const candidate = path.join(entries[index], SHIM_COMMAND);
    if (!isExecutableFile(candidate) || !isShimFile(candidate)) continue;
    installed = { file: candidate, directory: entries[index], index };
    break;
  }
  if (!installed && existsSync(path.join(FALLBACK_SHIM_DIR, SHIM_COMMAND))) {
    const file = path.join(FALLBACK_SHIM_DIR, SHIM_COMMAND);
    if (isShimFile(file)) installed = { file, directory: FALLBACK_SHIM_DIR, index: -1 };
  }

  return {
    installed: Boolean(installed),
    shim: installed?.file ?? null,
    real_codex: real?.file ?? null,
    // The distinction that matters: a shim can exist and still never run,
    // because something earlier on PATH answers to `codex` first.
    effective: Boolean(installed) && (!real || (installed.index >= 0 && installed.index < real.index)),
    on_path: Boolean(installed) && installed.index >= 0,
  };
}

export function installShim({
  environment = process.env,
  platform = process.platform,
  home = os.homedir(),
  checkout = SOURCE_ROOT,
} = {}) {
  // The shim is a bash script and PATH shadowing works differently under
  // PATHEXT, so Windows would need a `codex.cmd` written by different rules
  // rather than this file with a different extension. Refuse rather than
  // install something that cannot run.
  if (platform === "win32") {
    throw new Error(
      "The codex shim is not available on Windows. The tray still starts the router when it sees Codex running.",
    );
  }

  const real = resolveRealCodex(environment);
  if (!real) {
    throw new Error(
      "Codex is not on PATH, so there is nothing to wrap. Install Codex first, then run this again.",
    );
  }

  const choice = chooseShimDirectory(real, environment, home);
  mkdirSync(choice.directory, { recursive: true });
  const target = path.join(choice.directory, SHIM_COMMAND);

  // Refuse to overwrite anything that is not already our own shim. A file named
  // `codex` ahead of the real one is someone else's deliberate wrapper, and
  // replacing it silently would be indistinguishable from breaking their setup.
  if (existsSync(target) && !isShimFile(target)) {
    throw new Error(
      `${target} already exists and was not created by the router. Move it aside, or remove it, before installing the shim.`,
    );
  }

  // Resolve the recorded target through symlinks so the shim keeps working when
  // whatever put `codex` on PATH is rearranged. npm's bin entry is a relative
  // link into lib/node_modules and is exactly the kind of thing that moves.
  let recorded = real.file;
  try {
    recorded = realpathSync(real.file);
  } catch {
    // A dangling link is the caller's problem to fix; record what we were told.
  }

  writeFileSync(target, renderShim({ realCodex: recorded, checkout }), { mode: 0o755 });
  chmodSync(target, 0o755);

  return {
    ...shimStatus(environment),
    installed_to: target,
    wraps: recorded,
    needs_path_entry: choice.onPath ? null : choice.directory,
  };
}

export function uninstallShim(environment = process.env) {
  const removed = [];
  const candidates = [
    ...pathEntries(environment).map((directory) => path.join(directory, SHIM_COMMAND)),
    path.join(FALLBACK_SHIM_DIR, SHIM_COMMAND),
  ];

  for (const candidate of new Set(candidates)) {
    // Only ever delete a file that carries our marker. Everything else named
    // `codex` on this PATH belongs to somebody else.
    if (!existsSync(candidate) || !isShimFile(candidate)) continue;
    rmSync(candidate, { force: true });
    removed.push(candidate);
  }

  return { removed, ...shimStatus(environment) };
}

function describeSymlink(file) {
  try {
    return readlinkSync(file);
  } catch {
    return null;
  }
}

export function shimReport(environment = process.env) {
  const status = shimStatus(environment);
  return { ...status, real_codex_link: status.real_codex ? describeSymlink(status.real_codex) : null };
}
